apiVersion: v1
kind: Service
metadata:
  name: {{ include "sub2api.fullname" . }}-control
  labels:
    {{- include "sub2api.labels" . | nindent 4 }}
    app.kubernetes.io/component: control
spec:
  type: {{ .Values.controlService.type }}
  ports:
    - port: {{ .Values.controlService.port }}
      targetPort: frontend
      protocol: TCP
      name: http
  selector:
    {{- include "sub2api.control.selectorLabels" . | nindent 4 }}
