// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authemailverification"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AuthEmailVerificationDelete is the builder for deleting a AuthEmailVerification entity.
type AuthEmailVerificationDelete struct {
	config
	hooks    []Hook
	mutation *AuthEmailVerificationMutation
}

// Where appends a list predicates to the AuthEmailVerificationDelete builder.
func (_d *AuthEmailVerificationDelete) Where(ps ...predicate.AuthEmailVerification) *AuthEmailVerificationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthEmailVerificationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthEmailVerificationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthEmailVerificationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authemailverification.Table, sqlgraph.NewFieldSpec(authemailverification.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthEmailVerificationDeleteOne is the builder for deleting a single AuthEmailVerification entity.
type AuthEmailVerificationDeleteOne struct {
	_d *AuthEmailVerificationDelete
}

// Where appends a list predicates to the AuthEmailVerificationDelete builder.
func (_d *AuthEmailVerificationDeleteOne) Where(ps ...predicate.AuthEmailVerification) *AuthEmailVerificationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthEmailVerificationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authemailverification.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthEmailVerificationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
