// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authflow"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AuthFlowUpdate is the builder for updating AuthFlow entities.
type AuthFlowUpdate struct {
	config
	hooks    []Hook
	mutation *AuthFlowMutation
}

// Where appends a list predicates to the AuthFlowUpdate builder.
func (_u *AuthFlowUpdate) Where(ps ...predicate.AuthFlow) *AuthFlowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthFlowUpdate) SetUpdatedAt(v time.Time) *AuthFlowUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AuthFlowUpdate) SetProvider(v string) *AuthFlowUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableProvider(v *string) *AuthFlowUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *AuthFlowUpdate) SetPurpose(v string) *AuthFlowUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillablePurpose(v *string) *AuthFlowUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *AuthFlowUpdate) SetIssuer(v string) *AuthFlowUpdate {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableIssuer(v *string) *AuthFlowUpdate {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *AuthFlowUpdate) SetStateHash(v string) *AuthFlowUpdate {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableStateHash(v *string) *AuthFlowUpdate {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetCodeVerifier sets the "code_verifier" field.
func (_u *AuthFlowUpdate) SetCodeVerifier(v string) *AuthFlowUpdate {
	_u.mutation.SetCodeVerifier(v)
	return _u
}

// SetNillableCodeVerifier sets the "code_verifier" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableCodeVerifier(v *string) *AuthFlowUpdate {
	if v != nil {
		_u.SetCodeVerifier(*v)
	}
	return _u
}

// ClearCodeVerifier clears the value of the "code_verifier" field.
func (_u *AuthFlowUpdate) ClearCodeVerifier() *AuthFlowUpdate {
	_u.mutation.ClearCodeVerifier()
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *AuthFlowUpdate) SetNonce(v string) *AuthFlowUpdate {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableNonce(v *string) *AuthFlowUpdate {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// ClearNonce clears the value of the "nonce" field.
func (_u *AuthFlowUpdate) ClearNonce() *AuthFlowUpdate {
	_u.mutation.ClearNonce()
	return _u
}

// SetRedirectTo sets the "redirect_to" field.
func (_u *AuthFlowUpdate) SetRedirectTo(v string) *AuthFlowUpdate {
	_u.mutation.SetRedirectTo(v)
	return _u
}

// SetNillableRedirectTo sets the "redirect_to" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableRedirectTo(v *string) *AuthFlowUpdate {
	if v != nil {
		_u.SetRedirectTo(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthFlowUpdate) SetExpiresAt(v time.Time) *AuthFlowUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableExpiresAt(v *time.Time) *AuthFlowUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthFlowUpdate) SetConsumedAt(v time.Time) *AuthFlowUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthFlowUpdate) SetNillableConsumedAt(v *time.Time) *AuthFlowUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthFlowUpdate) ClearConsumedAt() *AuthFlowUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the AuthFlowMutation object of the builder.
func (_u *AuthFlowUpdate) Mutation() *AuthFlowMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthFlowUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthFlowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthFlowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthFlowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthFlowUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authflow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthFlowUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := authflow.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AuthFlow.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Purpose(); ok {
		if err := authflow.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AuthFlow.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StateHash(); ok {
		if err := authflow.StateHashValidator(v); err != nil {
			return &ValidationError{Name: "state_hash", err: fmt.Errorf(`ent: validator failed for field "AuthFlow.state_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthFlowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authflow.Table, authflow.Columns, sqlgraph.NewFieldSpec(authflow.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(authflow.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(authflow.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(authflow.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(authflow.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeVerifier(); ok {
		_spec.SetField(authflow.FieldCodeVerifier, field.TypeString, value)
	}
	if _u.mutation.CodeVerifierCleared() {
		_spec.ClearField(authflow.FieldCodeVerifier, field.TypeString)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(authflow.FieldNonce, field.TypeString, value)
	}
	if _u.mutation.NonceCleared() {
		_spec.ClearField(authflow.FieldNonce, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectTo(); ok {
		_spec.SetField(authflow.FieldRedirectTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authflow.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authflow.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authflow.FieldConsumedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthFlowUpdateOne is the builder for updating a single AuthFlow entity.
type AuthFlowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthFlowMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthFlowUpdateOne) SetUpdatedAt(v time.Time) *AuthFlowUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AuthFlowUpdateOne) SetProvider(v string) *AuthFlowUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableProvider(v *string) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *AuthFlowUpdateOne) SetPurpose(v string) *AuthFlowUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillablePurpose(v *string) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *AuthFlowUpdateOne) SetIssuer(v string) *AuthFlowUpdateOne {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableIssuer(v *string) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *AuthFlowUpdateOne) SetStateHash(v string) *AuthFlowUpdateOne {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableStateHash(v *string) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetCodeVerifier sets the "code_verifier" field.
func (_u *AuthFlowUpdateOne) SetCodeVerifier(v string) *AuthFlowUpdateOne {
	_u.mutation.SetCodeVerifier(v)
	return _u
}

// SetNillableCodeVerifier sets the "code_verifier" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableCodeVerifier(v *string) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetCodeVerifier(*v)
	}
	return _u
}

// ClearCodeVerifier clears the value of the "code_verifier" field.
func (_u *AuthFlowUpdateOne) ClearCodeVerifier() *AuthFlowUpdateOne {
	_u.mutation.ClearCodeVerifier()
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *AuthFlowUpdateOne) SetNonce(v string) *AuthFlowUpdateOne {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableNonce(v *string) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// ClearNonce clears the value of the "nonce" field.
func (_u *AuthFlowUpdateOne) ClearNonce() *AuthFlowUpdateOne {
	_u.mutation.ClearNonce()
	return _u
}

// SetRedirectTo sets the "redirect_to" field.
func (_u *AuthFlowUpdateOne) SetRedirectTo(v string) *AuthFlowUpdateOne {
	_u.mutation.SetRedirectTo(v)
	return _u
}

// SetNillableRedirectTo sets the "redirect_to" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableRedirectTo(v *string) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetRedirectTo(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthFlowUpdateOne) SetExpiresAt(v time.Time) *AuthFlowUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthFlowUpdateOne) SetConsumedAt(v time.Time) *AuthFlowUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthFlowUpdateOne) SetNillableConsumedAt(v *time.Time) *AuthFlowUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthFlowUpdateOne) ClearConsumedAt() *AuthFlowUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the AuthFlowMutation object of the builder.
func (_u *AuthFlowUpdateOne) Mutation() *AuthFlowMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthFlowUpdate builder.
func (_u *AuthFlowUpdateOne) Where(ps ...predicate.AuthFlow) *AuthFlowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthFlowUpdateOne) Select(field string, fields ...string) *AuthFlowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthFlow entity.
func (_u *AuthFlowUpdateOne) Save(ctx context.Context) (*AuthFlow, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthFlowUpdateOne) SaveX(ctx context.Context) *AuthFlow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthFlowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthFlowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthFlowUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authflow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthFlowUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := authflow.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AuthFlow.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Purpose(); ok {
		if err := authflow.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AuthFlow.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StateHash(); ok {
		if err := authflow.StateHashValidator(v); err != nil {
			return &ValidationError{Name: "state_hash", err: fmt.Errorf(`ent: validator failed for field "AuthFlow.state_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthFlowUpdateOne) sqlSave(ctx context.Context) (_node *AuthFlow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authflow.Table, authflow.Columns, sqlgraph.NewFieldSpec(authflow.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthFlow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authflow.FieldID)
		for _, f := range fields {
			if !authflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(authflow.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(authflow.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(authflow.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(authflow.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeVerifier(); ok {
		_spec.SetField(authflow.FieldCodeVerifier, field.TypeString, value)
	}
	if _u.mutation.CodeVerifierCleared() {
		_spec.ClearField(authflow.FieldCodeVerifier, field.TypeString)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(authflow.FieldNonce, field.TypeString, value)
	}
	if _u.mutation.NonceCleared() {
		_spec.ClearField(authflow.FieldNonce, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectTo(); ok {
		_spec.SetField(authflow.FieldRedirectTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authflow.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authflow.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authflow.FieldConsumedAt, field.TypeTime)
	}
	_node = &AuthFlow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
