// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authregistrationchallenge"
	"github.com/google/uuid"
)

// AuthRegistrationChallengeCreate is the builder for creating a AuthRegistrationChallenge entity.
type AuthRegistrationChallengeCreate struct {
	config
	mutation *AuthRegistrationChallengeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthRegistrationChallengeCreate) SetCreatedAt(v time.Time) *AuthRegistrationChallengeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableCreatedAt(v *time.Time) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthRegistrationChallengeCreate) SetUpdatedAt(v time.Time) *AuthRegistrationChallengeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableUpdatedAt(v *time.Time) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AuthRegistrationChallengeCreate) SetProvider(v string) *AuthRegistrationChallengeCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *AuthRegistrationChallengeCreate) SetIssuer(v string) *AuthRegistrationChallengeCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableIssuer(v *string) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetIssuer(*v)
	}
	return _c
}

// SetExternalSubject sets the "external_subject" field.
func (_c *AuthRegistrationChallengeCreate) SetExternalSubject(v string) *AuthRegistrationChallengeCreate {
	_c.mutation.SetExternalSubject(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AuthRegistrationChallengeCreate) SetEmail(v string) *AuthRegistrationChallengeCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetRegistrationEmail sets the "registration_email" field.
func (_c *AuthRegistrationChallengeCreate) SetRegistrationEmail(v string) *AuthRegistrationChallengeCreate {
	_c.mutation.SetRegistrationEmail(v)
	return _c
}

// SetNillableRegistrationEmail sets the "registration_email" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableRegistrationEmail(v *string) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetRegistrationEmail(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *AuthRegistrationChallengeCreate) SetUsername(v string) *AuthRegistrationChallengeCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableUsername(v *string) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetRedirectTo sets the "redirect_to" field.
func (_c *AuthRegistrationChallengeCreate) SetRedirectTo(v string) *AuthRegistrationChallengeCreate {
	_c.mutation.SetRedirectTo(v)
	return _c
}

// SetNillableRedirectTo sets the "redirect_to" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableRedirectTo(v *string) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetRedirectTo(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthRegistrationChallengeCreate) SetExpiresAt(v time.Time) *AuthRegistrationChallengeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *AuthRegistrationChallengeCreate) SetConsumedAt(v time.Time) *AuthRegistrationChallengeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableConsumedAt(v *time.Time) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthRegistrationChallengeCreate) SetID(v uuid.UUID) *AuthRegistrationChallengeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuthRegistrationChallengeCreate) SetNillableID(v *uuid.UUID) *AuthRegistrationChallengeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AuthRegistrationChallengeMutation object of the builder.
func (_c *AuthRegistrationChallengeCreate) Mutation() *AuthRegistrationChallengeMutation {
	return _c.mutation
}

// Save creates the AuthRegistrationChallenge in the database.
func (_c *AuthRegistrationChallengeCreate) Save(ctx context.Context) (*AuthRegistrationChallenge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthRegistrationChallengeCreate) SaveX(ctx context.Context) *AuthRegistrationChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthRegistrationChallengeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthRegistrationChallengeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthRegistrationChallengeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authregistrationchallenge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authregistrationchallenge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Issuer(); !ok {
		v := authregistrationchallenge.DefaultIssuer
		_c.mutation.SetIssuer(v)
	}
	if _, ok := _c.mutation.RegistrationEmail(); !ok {
		v := authregistrationchallenge.DefaultRegistrationEmail
		_c.mutation.SetRegistrationEmail(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := authregistrationchallenge.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.RedirectTo(); !ok {
		v := authregistrationchallenge.DefaultRedirectTo
		_c.mutation.SetRedirectTo(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := authregistrationchallenge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthRegistrationChallengeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.updated_at"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := authregistrationchallenge.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AuthRegistrationChallenge.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.issuer"`)}
	}
	if _, ok := _c.mutation.ExternalSubject(); !ok {
		return &ValidationError{Name: "external_subject", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.external_subject"`)}
	}
	if v, ok := _c.mutation.ExternalSubject(); ok {
		if err := authregistrationchallenge.ExternalSubjectValidator(v); err != nil {
			return &ValidationError{Name: "external_subject", err: fmt.Errorf(`ent: validator failed for field "AuthRegistrationChallenge.external_subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := authregistrationchallenge.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthRegistrationChallenge.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RegistrationEmail(); !ok {
		return &ValidationError{Name: "registration_email", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.registration_email"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.username"`)}
	}
	if _, ok := _c.mutation.RedirectTo(); !ok {
		return &ValidationError{Name: "redirect_to", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.redirect_to"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthRegistrationChallenge.expires_at"`)}
	}
	return nil
}

func (_c *AuthRegistrationChallengeCreate) sqlSave(ctx context.Context) (*AuthRegistrationChallenge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthRegistrationChallengeCreate) createSpec() (*AuthRegistrationChallenge, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthRegistrationChallenge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authregistrationchallenge.Table, sqlgraph.NewFieldSpec(authregistrationchallenge.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authregistrationchallenge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authregistrationchallenge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(authregistrationchallenge.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(authregistrationchallenge.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.ExternalSubject(); ok {
		_spec.SetField(authregistrationchallenge.FieldExternalSubject, field.TypeString, value)
		_node.ExternalSubject = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(authregistrationchallenge.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.RegistrationEmail(); ok {
		_spec.SetField(authregistrationchallenge.FieldRegistrationEmail, field.TypeString, value)
		_node.RegistrationEmail = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(authregistrationchallenge.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.RedirectTo(); ok {
		_spec.SetField(authregistrationchallenge.FieldRedirectTo, field.TypeString, value)
		_node.RedirectTo = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authregistrationchallenge.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(authregistrationchallenge.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthRegistrationChallenge.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthRegistrationChallengeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthRegistrationChallengeCreate) OnConflict(opts ...sql.ConflictOption) *AuthRegistrationChallengeUpsertOne {
	_c.conflict = opts
	return &AuthRegistrationChallengeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthRegistrationChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthRegistrationChallengeCreate) OnConflictColumns(columns ...string) *AuthRegistrationChallengeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthRegistrationChallengeUpsertOne{
		create: _c,
	}
}

type (
	// AuthRegistrationChallengeUpsertOne is the builder for "upsert"-ing
	//  one AuthRegistrationChallenge node.
	AuthRegistrationChallengeUpsertOne struct {
		create *AuthRegistrationChallengeCreate
	}

	// AuthRegistrationChallengeUpsert is the "OnConflict" setter.
	AuthRegistrationChallengeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthRegistrationChallengeUpsert) SetUpdatedAt(v time.Time) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateUpdatedAt() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldUpdatedAt)
	return u
}

// SetProvider sets the "provider" field.
func (u *AuthRegistrationChallengeUpsert) SetProvider(v string) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateProvider() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldProvider)
	return u
}

// SetIssuer sets the "issuer" field.
func (u *AuthRegistrationChallengeUpsert) SetIssuer(v string) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldIssuer, v)
	return u
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateIssuer() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldIssuer)
	return u
}

// SetExternalSubject sets the "external_subject" field.
func (u *AuthRegistrationChallengeUpsert) SetExternalSubject(v string) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldExternalSubject, v)
	return u
}

// UpdateExternalSubject sets the "external_subject" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateExternalSubject() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldExternalSubject)
	return u
}

// SetEmail sets the "email" field.
func (u *AuthRegistrationChallengeUpsert) SetEmail(v string) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateEmail() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldEmail)
	return u
}

// SetRegistrationEmail sets the "registration_email" field.
func (u *AuthRegistrationChallengeUpsert) SetRegistrationEmail(v string) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldRegistrationEmail, v)
	return u
}

// UpdateRegistrationEmail sets the "registration_email" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateRegistrationEmail() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldRegistrationEmail)
	return u
}

// SetUsername sets the "username" field.
func (u *AuthRegistrationChallengeUpsert) SetUsername(v string) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateUsername() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldUsername)
	return u
}

// SetRedirectTo sets the "redirect_to" field.
func (u *AuthRegistrationChallengeUpsert) SetRedirectTo(v string) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldRedirectTo, v)
	return u
}

// UpdateRedirectTo sets the "redirect_to" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateRedirectTo() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldRedirectTo)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthRegistrationChallengeUpsert) SetExpiresAt(v time.Time) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateExpiresAt() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldExpiresAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AuthRegistrationChallengeUpsert) SetConsumedAt(v time.Time) *AuthRegistrationChallengeUpsert {
	u.Set(authregistrationchallenge.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsert) UpdateConsumedAt() *AuthRegistrationChallengeUpsert {
	u.SetExcluded(authregistrationchallenge.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AuthRegistrationChallengeUpsert) ClearConsumedAt() *AuthRegistrationChallengeUpsert {
	u.SetNull(authregistrationchallenge.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthRegistrationChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authregistrationchallenge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthRegistrationChallengeUpsertOne) UpdateNewValues() *AuthRegistrationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authregistrationchallenge.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authregistrationchallenge.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthRegistrationChallenge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthRegistrationChallengeUpsertOne) Ignore() *AuthRegistrationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthRegistrationChallengeUpsertOne) DoNothing() *AuthRegistrationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthRegistrationChallengeCreate.OnConflict
// documentation for more info.
func (u *AuthRegistrationChallengeUpsertOne) Update(set func(*AuthRegistrationChallengeUpsert)) *AuthRegistrationChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthRegistrationChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthRegistrationChallengeUpsertOne) SetUpdatedAt(v time.Time) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateUpdatedAt() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProvider sets the "provider" field.
func (u *AuthRegistrationChallengeUpsertOne) SetProvider(v string) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateProvider() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateProvider()
	})
}

// SetIssuer sets the "issuer" field.
func (u *AuthRegistrationChallengeUpsertOne) SetIssuer(v string) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateIssuer() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateIssuer()
	})
}

// SetExternalSubject sets the "external_subject" field.
func (u *AuthRegistrationChallengeUpsertOne) SetExternalSubject(v string) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetExternalSubject(v)
	})
}

// UpdateExternalSubject sets the "external_subject" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateExternalSubject() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateExternalSubject()
	})
}

// SetEmail sets the "email" field.
func (u *AuthRegistrationChallengeUpsertOne) SetEmail(v string) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateEmail() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateEmail()
	})
}

// SetRegistrationEmail sets the "registration_email" field.
func (u *AuthRegistrationChallengeUpsertOne) SetRegistrationEmail(v string) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetRegistrationEmail(v)
	})
}

// UpdateRegistrationEmail sets the "registration_email" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateRegistrationEmail() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateRegistrationEmail()
	})
}

// SetUsername sets the "username" field.
func (u *AuthRegistrationChallengeUpsertOne) SetUsername(v string) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateUsername() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateUsername()
	})
}

// SetRedirectTo sets the "redirect_to" field.
func (u *AuthRegistrationChallengeUpsertOne) SetRedirectTo(v string) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetRedirectTo(v)
	})
}

// UpdateRedirectTo sets the "redirect_to" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateRedirectTo() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateRedirectTo()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthRegistrationChallengeUpsertOne) SetExpiresAt(v time.Time) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateExpiresAt() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AuthRegistrationChallengeUpsertOne) SetConsumedAt(v time.Time) *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertOne) UpdateConsumedAt() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AuthRegistrationChallengeUpsertOne) ClearConsumedAt() *AuthRegistrationChallengeUpsertOne {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *AuthRegistrationChallengeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthRegistrationChallengeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthRegistrationChallengeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthRegistrationChallengeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthRegistrationChallengeUpsertOne.ID is not supported by MySQL driver. Use AuthRegistrationChallengeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthRegistrationChallengeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthRegistrationChallengeCreateBulk is the builder for creating many AuthRegistrationChallenge entities in bulk.
type AuthRegistrationChallengeCreateBulk struct {
	config
	err      error
	builders []*AuthRegistrationChallengeCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthRegistrationChallenge entities in the database.
func (_c *AuthRegistrationChallengeCreateBulk) Save(ctx context.Context) ([]*AuthRegistrationChallenge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthRegistrationChallenge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthRegistrationChallengeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthRegistrationChallengeCreateBulk) SaveX(ctx context.Context) []*AuthRegistrationChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthRegistrationChallengeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthRegistrationChallengeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthRegistrationChallenge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthRegistrationChallengeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthRegistrationChallengeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthRegistrationChallengeUpsertBulk {
	_c.conflict = opts
	return &AuthRegistrationChallengeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthRegistrationChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthRegistrationChallengeCreateBulk) OnConflictColumns(columns ...string) *AuthRegistrationChallengeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthRegistrationChallengeUpsertBulk{
		create: _c,
	}
}

// AuthRegistrationChallengeUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthRegistrationChallenge nodes.
type AuthRegistrationChallengeUpsertBulk struct {
	create *AuthRegistrationChallengeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthRegistrationChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authregistrationchallenge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthRegistrationChallengeUpsertBulk) UpdateNewValues() *AuthRegistrationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authregistrationchallenge.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authregistrationchallenge.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthRegistrationChallenge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthRegistrationChallengeUpsertBulk) Ignore() *AuthRegistrationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthRegistrationChallengeUpsertBulk) DoNothing() *AuthRegistrationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthRegistrationChallengeCreateBulk.OnConflict
// documentation for more info.
func (u *AuthRegistrationChallengeUpsertBulk) Update(set func(*AuthRegistrationChallengeUpsert)) *AuthRegistrationChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthRegistrationChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetUpdatedAt(v time.Time) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateUpdatedAt() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProvider sets the "provider" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetProvider(v string) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateProvider() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateProvider()
	})
}

// SetIssuer sets the "issuer" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetIssuer(v string) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateIssuer() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateIssuer()
	})
}

// SetExternalSubject sets the "external_subject" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetExternalSubject(v string) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetExternalSubject(v)
	})
}

// UpdateExternalSubject sets the "external_subject" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateExternalSubject() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateExternalSubject()
	})
}

// SetEmail sets the "email" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetEmail(v string) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateEmail() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateEmail()
	})
}

// SetRegistrationEmail sets the "registration_email" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetRegistrationEmail(v string) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetRegistrationEmail(v)
	})
}

// UpdateRegistrationEmail sets the "registration_email" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateRegistrationEmail() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateRegistrationEmail()
	})
}

// SetUsername sets the "username" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetUsername(v string) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateUsername() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateUsername()
	})
}

// SetRedirectTo sets the "redirect_to" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetRedirectTo(v string) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetRedirectTo(v)
	})
}

// UpdateRedirectTo sets the "redirect_to" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateRedirectTo() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateRedirectTo()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetExpiresAt(v time.Time) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateExpiresAt() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AuthRegistrationChallengeUpsertBulk) SetConsumedAt(v time.Time) *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AuthRegistrationChallengeUpsertBulk) UpdateConsumedAt() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AuthRegistrationChallengeUpsertBulk) ClearConsumedAt() *AuthRegistrationChallengeUpsertBulk {
	return u.Update(func(s *AuthRegistrationChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *AuthRegistrationChallengeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthRegistrationChallengeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthRegistrationChallengeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthRegistrationChallengeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
