// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authrefreshtoken"
	"github.com/google/uuid"
)

// AuthRefreshTokenCreate is the builder for creating a AuthRefreshToken entity.
type AuthRefreshTokenCreate struct {
	config
	mutation *AuthRefreshTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthRefreshTokenCreate) SetCreatedAt(v time.Time) *AuthRefreshTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthRefreshTokenCreate) SetNillableCreatedAt(v *time.Time) *AuthRefreshTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthRefreshTokenCreate) SetUpdatedAt(v time.Time) *AuthRefreshTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthRefreshTokenCreate) SetNillableUpdatedAt(v *time.Time) *AuthRefreshTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSid sets the "sid" field.
func (_c *AuthRefreshTokenCreate) SetSid(v uuid.UUID) *AuthRefreshTokenCreate {
	_c.mutation.SetSid(v)
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *AuthRefreshTokenCreate) SetSubjectID(v uuid.UUID) *AuthRefreshTokenCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_c *AuthRefreshTokenCreate) SetLegacyUserID(v int64) *AuthRefreshTokenCreate {
	_c.mutation.SetLegacyUserID(v)
	return _c
}

// SetIdleExpiresAt sets the "idle_expires_at" field.
func (_c *AuthRefreshTokenCreate) SetIdleExpiresAt(v time.Time) *AuthRefreshTokenCreate {
	_c.mutation.SetIdleExpiresAt(v)
	return _c
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (_c *AuthRefreshTokenCreate) SetAbsoluteExpiresAt(v time.Time) *AuthRefreshTokenCreate {
	_c.mutation.SetAbsoluteExpiresAt(v)
	return _c
}

// SetRotatedAt sets the "rotated_at" field.
func (_c *AuthRefreshTokenCreate) SetRotatedAt(v time.Time) *AuthRefreshTokenCreate {
	_c.mutation.SetRotatedAt(v)
	return _c
}

// SetNillableRotatedAt sets the "rotated_at" field if the given value is not nil.
func (_c *AuthRefreshTokenCreate) SetNillableRotatedAt(v *time.Time) *AuthRefreshTokenCreate {
	if v != nil {
		_c.SetRotatedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AuthRefreshTokenCreate) SetRevokedAt(v time.Time) *AuthRefreshTokenCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AuthRefreshTokenCreate) SetNillableRevokedAt(v *time.Time) *AuthRefreshTokenCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetReplacedByTokenHash sets the "replaced_by_token_hash" field.
func (_c *AuthRefreshTokenCreate) SetReplacedByTokenHash(v string) *AuthRefreshTokenCreate {
	_c.mutation.SetReplacedByTokenHash(v)
	return _c
}

// SetNillableReplacedByTokenHash sets the "replaced_by_token_hash" field if the given value is not nil.
func (_c *AuthRefreshTokenCreate) SetNillableReplacedByTokenHash(v *string) *AuthRefreshTokenCreate {
	if v != nil {
		_c.SetReplacedByTokenHash(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthRefreshTokenCreate) SetID(v string) *AuthRefreshTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthRefreshTokenMutation object of the builder.
func (_c *AuthRefreshTokenCreate) Mutation() *AuthRefreshTokenMutation {
	return _c.mutation
}

// Save creates the AuthRefreshToken in the database.
func (_c *AuthRefreshTokenCreate) Save(ctx context.Context) (*AuthRefreshToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthRefreshTokenCreate) SaveX(ctx context.Context) *AuthRefreshToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthRefreshTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthRefreshTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthRefreshTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authrefreshtoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authrefreshtoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthRefreshTokenCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthRefreshToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthRefreshToken.updated_at"`)}
	}
	if _, ok := _c.mutation.Sid(); !ok {
		return &ValidationError{Name: "sid", err: errors.New(`ent: missing required field "AuthRefreshToken.sid"`)}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "AuthRefreshToken.subject_id"`)}
	}
	if _, ok := _c.mutation.LegacyUserID(); !ok {
		return &ValidationError{Name: "legacy_user_id", err: errors.New(`ent: missing required field "AuthRefreshToken.legacy_user_id"`)}
	}
	if _, ok := _c.mutation.IdleExpiresAt(); !ok {
		return &ValidationError{Name: "idle_expires_at", err: errors.New(`ent: missing required field "AuthRefreshToken.idle_expires_at"`)}
	}
	if _, ok := _c.mutation.AbsoluteExpiresAt(); !ok {
		return &ValidationError{Name: "absolute_expires_at", err: errors.New(`ent: missing required field "AuthRefreshToken.absolute_expires_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := authrefreshtoken.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AuthRefreshToken.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AuthRefreshTokenCreate) sqlSave(ctx context.Context) (*AuthRefreshToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuthRefreshToken.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthRefreshTokenCreate) createSpec() (*AuthRefreshToken, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthRefreshToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authrefreshtoken.Table, sqlgraph.NewFieldSpec(authrefreshtoken.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authrefreshtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authrefreshtoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Sid(); ok {
		_spec.SetField(authrefreshtoken.FieldSid, field.TypeUUID, value)
		_node.Sid = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(authrefreshtoken.FieldSubjectID, field.TypeUUID, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.LegacyUserID(); ok {
		_spec.SetField(authrefreshtoken.FieldLegacyUserID, field.TypeInt64, value)
		_node.LegacyUserID = value
	}
	if value, ok := _c.mutation.IdleExpiresAt(); ok {
		_spec.SetField(authrefreshtoken.FieldIdleExpiresAt, field.TypeTime, value)
		_node.IdleExpiresAt = value
	}
	if value, ok := _c.mutation.AbsoluteExpiresAt(); ok {
		_spec.SetField(authrefreshtoken.FieldAbsoluteExpiresAt, field.TypeTime, value)
		_node.AbsoluteExpiresAt = value
	}
	if value, ok := _c.mutation.RotatedAt(); ok {
		_spec.SetField(authrefreshtoken.FieldRotatedAt, field.TypeTime, value)
		_node.RotatedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(authrefreshtoken.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.ReplacedByTokenHash(); ok {
		_spec.SetField(authrefreshtoken.FieldReplacedByTokenHash, field.TypeString, value)
		_node.ReplacedByTokenHash = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthRefreshToken.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthRefreshTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthRefreshTokenCreate) OnConflict(opts ...sql.ConflictOption) *AuthRefreshTokenUpsertOne {
	_c.conflict = opts
	return &AuthRefreshTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthRefreshToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthRefreshTokenCreate) OnConflictColumns(columns ...string) *AuthRefreshTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthRefreshTokenUpsertOne{
		create: _c,
	}
}

type (
	// AuthRefreshTokenUpsertOne is the builder for "upsert"-ing
	//  one AuthRefreshToken node.
	AuthRefreshTokenUpsertOne struct {
		create *AuthRefreshTokenCreate
	}

	// AuthRefreshTokenUpsert is the "OnConflict" setter.
	AuthRefreshTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthRefreshTokenUpsert) SetUpdatedAt(v time.Time) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateUpdatedAt() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldUpdatedAt)
	return u
}

// SetSid sets the "sid" field.
func (u *AuthRefreshTokenUpsert) SetSid(v uuid.UUID) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldSid, v)
	return u
}

// UpdateSid sets the "sid" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateSid() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldSid)
	return u
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthRefreshTokenUpsert) SetSubjectID(v uuid.UUID) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldSubjectID, v)
	return u
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateSubjectID() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldSubjectID)
	return u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthRefreshTokenUpsert) SetLegacyUserID(v int64) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldLegacyUserID, v)
	return u
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateLegacyUserID() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldLegacyUserID)
	return u
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthRefreshTokenUpsert) AddLegacyUserID(v int64) *AuthRefreshTokenUpsert {
	u.Add(authrefreshtoken.FieldLegacyUserID, v)
	return u
}

// SetIdleExpiresAt sets the "idle_expires_at" field.
func (u *AuthRefreshTokenUpsert) SetIdleExpiresAt(v time.Time) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldIdleExpiresAt, v)
	return u
}

// UpdateIdleExpiresAt sets the "idle_expires_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateIdleExpiresAt() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldIdleExpiresAt)
	return u
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (u *AuthRefreshTokenUpsert) SetAbsoluteExpiresAt(v time.Time) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldAbsoluteExpiresAt, v)
	return u
}

// UpdateAbsoluteExpiresAt sets the "absolute_expires_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateAbsoluteExpiresAt() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldAbsoluteExpiresAt)
	return u
}

// SetRotatedAt sets the "rotated_at" field.
func (u *AuthRefreshTokenUpsert) SetRotatedAt(v time.Time) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldRotatedAt, v)
	return u
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateRotatedAt() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldRotatedAt)
	return u
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *AuthRefreshTokenUpsert) ClearRotatedAt() *AuthRefreshTokenUpsert {
	u.SetNull(authrefreshtoken.FieldRotatedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthRefreshTokenUpsert) SetRevokedAt(v time.Time) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateRevokedAt() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthRefreshTokenUpsert) ClearRevokedAt() *AuthRefreshTokenUpsert {
	u.SetNull(authrefreshtoken.FieldRevokedAt)
	return u
}

// SetReplacedByTokenHash sets the "replaced_by_token_hash" field.
func (u *AuthRefreshTokenUpsert) SetReplacedByTokenHash(v string) *AuthRefreshTokenUpsert {
	u.Set(authrefreshtoken.FieldReplacedByTokenHash, v)
	return u
}

// UpdateReplacedByTokenHash sets the "replaced_by_token_hash" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsert) UpdateReplacedByTokenHash() *AuthRefreshTokenUpsert {
	u.SetExcluded(authrefreshtoken.FieldReplacedByTokenHash)
	return u
}

// ClearReplacedByTokenHash clears the value of the "replaced_by_token_hash" field.
func (u *AuthRefreshTokenUpsert) ClearReplacedByTokenHash() *AuthRefreshTokenUpsert {
	u.SetNull(authrefreshtoken.FieldReplacedByTokenHash)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthRefreshToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authrefreshtoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthRefreshTokenUpsertOne) UpdateNewValues() *AuthRefreshTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authrefreshtoken.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authrefreshtoken.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthRefreshToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthRefreshTokenUpsertOne) Ignore() *AuthRefreshTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthRefreshTokenUpsertOne) DoNothing() *AuthRefreshTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthRefreshTokenCreate.OnConflict
// documentation for more info.
func (u *AuthRefreshTokenUpsertOne) Update(set func(*AuthRefreshTokenUpsert)) *AuthRefreshTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthRefreshTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthRefreshTokenUpsertOne) SetUpdatedAt(v time.Time) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateUpdatedAt() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSid sets the "sid" field.
func (u *AuthRefreshTokenUpsertOne) SetSid(v uuid.UUID) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetSid(v)
	})
}

// UpdateSid sets the "sid" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateSid() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateSid()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthRefreshTokenUpsertOne) SetSubjectID(v uuid.UUID) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateSubjectID() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateSubjectID()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthRefreshTokenUpsertOne) SetLegacyUserID(v int64) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthRefreshTokenUpsertOne) AddLegacyUserID(v int64) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateLegacyUserID() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetIdleExpiresAt sets the "idle_expires_at" field.
func (u *AuthRefreshTokenUpsertOne) SetIdleExpiresAt(v time.Time) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetIdleExpiresAt(v)
	})
}

// UpdateIdleExpiresAt sets the "idle_expires_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateIdleExpiresAt() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateIdleExpiresAt()
	})
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (u *AuthRefreshTokenUpsertOne) SetAbsoluteExpiresAt(v time.Time) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetAbsoluteExpiresAt(v)
	})
}

// UpdateAbsoluteExpiresAt sets the "absolute_expires_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateAbsoluteExpiresAt() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateAbsoluteExpiresAt()
	})
}

// SetRotatedAt sets the "rotated_at" field.
func (u *AuthRefreshTokenUpsertOne) SetRotatedAt(v time.Time) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetRotatedAt(v)
	})
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateRotatedAt() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateRotatedAt()
	})
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *AuthRefreshTokenUpsertOne) ClearRotatedAt() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.ClearRotatedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthRefreshTokenUpsertOne) SetRevokedAt(v time.Time) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateRevokedAt() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthRefreshTokenUpsertOne) ClearRevokedAt() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.ClearRevokedAt()
	})
}

// SetReplacedByTokenHash sets the "replaced_by_token_hash" field.
func (u *AuthRefreshTokenUpsertOne) SetReplacedByTokenHash(v string) *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetReplacedByTokenHash(v)
	})
}

// UpdateReplacedByTokenHash sets the "replaced_by_token_hash" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertOne) UpdateReplacedByTokenHash() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateReplacedByTokenHash()
	})
}

// ClearReplacedByTokenHash clears the value of the "replaced_by_token_hash" field.
func (u *AuthRefreshTokenUpsertOne) ClearReplacedByTokenHash() *AuthRefreshTokenUpsertOne {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.ClearReplacedByTokenHash()
	})
}

// Exec executes the query.
func (u *AuthRefreshTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthRefreshTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthRefreshTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthRefreshTokenUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthRefreshTokenUpsertOne.ID is not supported by MySQL driver. Use AuthRefreshTokenUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthRefreshTokenUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthRefreshTokenCreateBulk is the builder for creating many AuthRefreshToken entities in bulk.
type AuthRefreshTokenCreateBulk struct {
	config
	err      error
	builders []*AuthRefreshTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthRefreshToken entities in the database.
func (_c *AuthRefreshTokenCreateBulk) Save(ctx context.Context) ([]*AuthRefreshToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthRefreshToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthRefreshTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthRefreshTokenCreateBulk) SaveX(ctx context.Context) []*AuthRefreshToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthRefreshTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthRefreshTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthRefreshToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthRefreshTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthRefreshTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthRefreshTokenUpsertBulk {
	_c.conflict = opts
	return &AuthRefreshTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthRefreshToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthRefreshTokenCreateBulk) OnConflictColumns(columns ...string) *AuthRefreshTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthRefreshTokenUpsertBulk{
		create: _c,
	}
}

// AuthRefreshTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthRefreshToken nodes.
type AuthRefreshTokenUpsertBulk struct {
	create *AuthRefreshTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthRefreshToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authrefreshtoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthRefreshTokenUpsertBulk) UpdateNewValues() *AuthRefreshTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authrefreshtoken.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authrefreshtoken.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthRefreshToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthRefreshTokenUpsertBulk) Ignore() *AuthRefreshTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthRefreshTokenUpsertBulk) DoNothing() *AuthRefreshTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthRefreshTokenCreateBulk.OnConflict
// documentation for more info.
func (u *AuthRefreshTokenUpsertBulk) Update(set func(*AuthRefreshTokenUpsert)) *AuthRefreshTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthRefreshTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthRefreshTokenUpsertBulk) SetUpdatedAt(v time.Time) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateUpdatedAt() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSid sets the "sid" field.
func (u *AuthRefreshTokenUpsertBulk) SetSid(v uuid.UUID) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetSid(v)
	})
}

// UpdateSid sets the "sid" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateSid() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateSid()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthRefreshTokenUpsertBulk) SetSubjectID(v uuid.UUID) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateSubjectID() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateSubjectID()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthRefreshTokenUpsertBulk) SetLegacyUserID(v int64) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthRefreshTokenUpsertBulk) AddLegacyUserID(v int64) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateLegacyUserID() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetIdleExpiresAt sets the "idle_expires_at" field.
func (u *AuthRefreshTokenUpsertBulk) SetIdleExpiresAt(v time.Time) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetIdleExpiresAt(v)
	})
}

// UpdateIdleExpiresAt sets the "idle_expires_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateIdleExpiresAt() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateIdleExpiresAt()
	})
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (u *AuthRefreshTokenUpsertBulk) SetAbsoluteExpiresAt(v time.Time) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetAbsoluteExpiresAt(v)
	})
}

// UpdateAbsoluteExpiresAt sets the "absolute_expires_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateAbsoluteExpiresAt() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateAbsoluteExpiresAt()
	})
}

// SetRotatedAt sets the "rotated_at" field.
func (u *AuthRefreshTokenUpsertBulk) SetRotatedAt(v time.Time) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetRotatedAt(v)
	})
}

// UpdateRotatedAt sets the "rotated_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateRotatedAt() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateRotatedAt()
	})
}

// ClearRotatedAt clears the value of the "rotated_at" field.
func (u *AuthRefreshTokenUpsertBulk) ClearRotatedAt() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.ClearRotatedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthRefreshTokenUpsertBulk) SetRevokedAt(v time.Time) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateRevokedAt() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthRefreshTokenUpsertBulk) ClearRevokedAt() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.ClearRevokedAt()
	})
}

// SetReplacedByTokenHash sets the "replaced_by_token_hash" field.
func (u *AuthRefreshTokenUpsertBulk) SetReplacedByTokenHash(v string) *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.SetReplacedByTokenHash(v)
	})
}

// UpdateReplacedByTokenHash sets the "replaced_by_token_hash" field to the value that was provided on create.
func (u *AuthRefreshTokenUpsertBulk) UpdateReplacedByTokenHash() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.UpdateReplacedByTokenHash()
	})
}

// ClearReplacedByTokenHash clears the value of the "replaced_by_token_hash" field.
func (u *AuthRefreshTokenUpsertBulk) ClearReplacedByTokenHash() *AuthRefreshTokenUpsertBulk {
	return u.Update(func(s *AuthRefreshTokenUpsert) {
		s.ClearReplacedByTokenHash()
	})
}

// Exec executes the query.
func (u *AuthRefreshTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthRefreshTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthRefreshTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthRefreshTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
