// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authsession"
	"github.com/google/uuid"
)

// AuthSessionCreate is the builder for creating a AuthSession entity.
type AuthSessionCreate struct {
	config
	mutation *AuthSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthSessionCreate) SetCreatedAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableCreatedAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthSessionCreate) SetUpdatedAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableUpdatedAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *AuthSessionCreate) SetSubjectID(v uuid.UUID) *AuthSessionCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_c *AuthSessionCreate) SetLegacyUserID(v int64) *AuthSessionCreate {
	_c.mutation.SetLegacyUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AuthSessionCreate) SetStatus(v string) *AuthSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableStatus(v *string) *AuthSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAmr sets the "amr" field.
func (_c *AuthSessionCreate) SetAmr(v string) *AuthSessionCreate {
	_c.mutation.SetAmr(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *AuthSessionCreate) SetLastSeenAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthSessionCreate) SetExpiresAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (_c *AuthSessionCreate) SetAbsoluteExpiresAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetAbsoluteExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AuthSessionCreate) SetRevokedAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableRevokedAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetCurrentRefreshTokenHash sets the "current_refresh_token_hash" field.
func (_c *AuthSessionCreate) SetCurrentRefreshTokenHash(v string) *AuthSessionCreate {
	_c.mutation.SetCurrentRefreshTokenHash(v)
	return _c
}

// SetAuthVersion sets the "auth_version" field.
func (_c *AuthSessionCreate) SetAuthVersion(v int64) *AuthSessionCreate {
	_c.mutation.SetAuthVersion(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AuthSessionCreate) SetID(v uuid.UUID) *AuthSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableID(v *uuid.UUID) *AuthSessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_c *AuthSessionCreate) Mutation() *AuthSessionMutation {
	return _c.mutation
}

// Save creates the AuthSession in the database.
func (_c *AuthSessionCreate) Save(ctx context.Context) (*AuthSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthSessionCreate) SaveX(ctx context.Context) *AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := authsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := authsession.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthSession.updated_at"`)}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "AuthSession.subject_id"`)}
	}
	if _, ok := _c.mutation.LegacyUserID(); !ok {
		return &ValidationError{Name: "legacy_user_id", err: errors.New(`ent: missing required field "AuthSession.legacy_user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AuthSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := authsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuthSession.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amr(); !ok {
		return &ValidationError{Name: "amr", err: errors.New(`ent: missing required field "AuthSession.amr"`)}
	}
	if v, ok := _c.mutation.Amr(); ok {
		if err := authsession.AmrValidator(v); err != nil {
			return &ValidationError{Name: "amr", err: fmt.Errorf(`ent: validator failed for field "AuthSession.amr": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "AuthSession.last_seen_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthSession.expires_at"`)}
	}
	if _, ok := _c.mutation.AbsoluteExpiresAt(); !ok {
		return &ValidationError{Name: "absolute_expires_at", err: errors.New(`ent: missing required field "AuthSession.absolute_expires_at"`)}
	}
	if _, ok := _c.mutation.CurrentRefreshTokenHash(); !ok {
		return &ValidationError{Name: "current_refresh_token_hash", err: errors.New(`ent: missing required field "AuthSession.current_refresh_token_hash"`)}
	}
	if v, ok := _c.mutation.CurrentRefreshTokenHash(); ok {
		if err := authsession.CurrentRefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "current_refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "AuthSession.current_refresh_token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthVersion(); !ok {
		return &ValidationError{Name: "auth_version", err: errors.New(`ent: missing required field "AuthSession.auth_version"`)}
	}
	return nil
}

func (_c *AuthSessionCreate) sqlSave(ctx context.Context) (*AuthSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthSessionCreate) createSpec() (*AuthSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authsession.Table, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(authsession.FieldSubjectID, field.TypeUUID, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.LegacyUserID(); ok {
		_spec.SetField(authsession.FieldLegacyUserID, field.TypeInt64, value)
		_node.LegacyUserID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(authsession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Amr(); ok {
		_spec.SetField(authsession.FieldAmr, field.TypeString, value)
		_node.Amr = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(authsession.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.AbsoluteExpiresAt(); ok {
		_spec.SetField(authsession.FieldAbsoluteExpiresAt, field.TypeTime, value)
		_node.AbsoluteExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(authsession.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.CurrentRefreshTokenHash(); ok {
		_spec.SetField(authsession.FieldCurrentRefreshTokenHash, field.TypeString, value)
		_node.CurrentRefreshTokenHash = value
	}
	if value, ok := _c.mutation.AuthVersion(); ok {
		_spec.SetField(authsession.FieldAuthVersion, field.TypeInt64, value)
		_node.AuthVersion = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthSession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthSessionCreate) OnConflict(opts ...sql.ConflictOption) *AuthSessionUpsertOne {
	_c.conflict = opts
	return &AuthSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthSessionCreate) OnConflictColumns(columns ...string) *AuthSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthSessionUpsertOne{
		create: _c,
	}
}

type (
	// AuthSessionUpsertOne is the builder for "upsert"-ing
	//  one AuthSession node.
	AuthSessionUpsertOne struct {
		create *AuthSessionCreate
	}

	// AuthSessionUpsert is the "OnConflict" setter.
	AuthSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthSessionUpsert) SetUpdatedAt(v time.Time) *AuthSessionUpsert {
	u.Set(authsession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateUpdatedAt() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldUpdatedAt)
	return u
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthSessionUpsert) SetSubjectID(v uuid.UUID) *AuthSessionUpsert {
	u.Set(authsession.FieldSubjectID, v)
	return u
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateSubjectID() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldSubjectID)
	return u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthSessionUpsert) SetLegacyUserID(v int64) *AuthSessionUpsert {
	u.Set(authsession.FieldLegacyUserID, v)
	return u
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateLegacyUserID() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldLegacyUserID)
	return u
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthSessionUpsert) AddLegacyUserID(v int64) *AuthSessionUpsert {
	u.Add(authsession.FieldLegacyUserID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *AuthSessionUpsert) SetStatus(v string) *AuthSessionUpsert {
	u.Set(authsession.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateStatus() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldStatus)
	return u
}

// SetAmr sets the "amr" field.
func (u *AuthSessionUpsert) SetAmr(v string) *AuthSessionUpsert {
	u.Set(authsession.FieldAmr, v)
	return u
}

// UpdateAmr sets the "amr" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateAmr() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldAmr)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AuthSessionUpsert) SetLastSeenAt(v time.Time) *AuthSessionUpsert {
	u.Set(authsession.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateLastSeenAt() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldLastSeenAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthSessionUpsert) SetExpiresAt(v time.Time) *AuthSessionUpsert {
	u.Set(authsession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateExpiresAt() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldExpiresAt)
	return u
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (u *AuthSessionUpsert) SetAbsoluteExpiresAt(v time.Time) *AuthSessionUpsert {
	u.Set(authsession.FieldAbsoluteExpiresAt, v)
	return u
}

// UpdateAbsoluteExpiresAt sets the "absolute_expires_at" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateAbsoluteExpiresAt() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldAbsoluteExpiresAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthSessionUpsert) SetRevokedAt(v time.Time) *AuthSessionUpsert {
	u.Set(authsession.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateRevokedAt() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthSessionUpsert) ClearRevokedAt() *AuthSessionUpsert {
	u.SetNull(authsession.FieldRevokedAt)
	return u
}

// SetCurrentRefreshTokenHash sets the "current_refresh_token_hash" field.
func (u *AuthSessionUpsert) SetCurrentRefreshTokenHash(v string) *AuthSessionUpsert {
	u.Set(authsession.FieldCurrentRefreshTokenHash, v)
	return u
}

// UpdateCurrentRefreshTokenHash sets the "current_refresh_token_hash" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateCurrentRefreshTokenHash() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldCurrentRefreshTokenHash)
	return u
}

// SetAuthVersion sets the "auth_version" field.
func (u *AuthSessionUpsert) SetAuthVersion(v int64) *AuthSessionUpsert {
	u.Set(authsession.FieldAuthVersion, v)
	return u
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateAuthVersion() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldAuthVersion)
	return u
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *AuthSessionUpsert) AddAuthVersion(v int64) *AuthSessionUpsert {
	u.Add(authsession.FieldAuthVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authsession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthSessionUpsertOne) UpdateNewValues() *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authsession.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authsession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthSessionUpsertOne) Ignore() *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthSessionUpsertOne) DoNothing() *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthSessionCreate.OnConflict
// documentation for more info.
func (u *AuthSessionUpsertOne) Update(set func(*AuthSessionUpsert)) *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthSessionUpsertOne) SetUpdatedAt(v time.Time) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateUpdatedAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthSessionUpsertOne) SetSubjectID(v uuid.UUID) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateSubjectID() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateSubjectID()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthSessionUpsertOne) SetLegacyUserID(v int64) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthSessionUpsertOne) AddLegacyUserID(v int64) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateLegacyUserID() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetStatus sets the "status" field.
func (u *AuthSessionUpsertOne) SetStatus(v string) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateStatus() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetAmr sets the "amr" field.
func (u *AuthSessionUpsertOne) SetAmr(v string) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetAmr(v)
	})
}

// UpdateAmr sets the "amr" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateAmr() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateAmr()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AuthSessionUpsertOne) SetLastSeenAt(v time.Time) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateLastSeenAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthSessionUpsertOne) SetExpiresAt(v time.Time) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateExpiresAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (u *AuthSessionUpsertOne) SetAbsoluteExpiresAt(v time.Time) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetAbsoluteExpiresAt(v)
	})
}

// UpdateAbsoluteExpiresAt sets the "absolute_expires_at" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateAbsoluteExpiresAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateAbsoluteExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthSessionUpsertOne) SetRevokedAt(v time.Time) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateRevokedAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthSessionUpsertOne) ClearRevokedAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// SetCurrentRefreshTokenHash sets the "current_refresh_token_hash" field.
func (u *AuthSessionUpsertOne) SetCurrentRefreshTokenHash(v string) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetCurrentRefreshTokenHash(v)
	})
}

// UpdateCurrentRefreshTokenHash sets the "current_refresh_token_hash" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateCurrentRefreshTokenHash() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateCurrentRefreshTokenHash()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *AuthSessionUpsertOne) SetAuthVersion(v int64) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *AuthSessionUpsertOne) AddAuthVersion(v int64) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateAuthVersion() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateAuthVersion()
	})
}

// Exec executes the query.
func (u *AuthSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthSessionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthSessionUpsertOne.ID is not supported by MySQL driver. Use AuthSessionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthSessionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthSessionCreateBulk is the builder for creating many AuthSession entities in bulk.
type AuthSessionCreateBulk struct {
	config
	err      error
	builders []*AuthSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthSession entities in the database.
func (_c *AuthSessionCreateBulk) Save(ctx context.Context) ([]*AuthSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) SaveX(ctx context.Context) []*AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthSessionUpsertBulk {
	_c.conflict = opts
	return &AuthSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthSessionCreateBulk) OnConflictColumns(columns ...string) *AuthSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthSessionUpsertBulk{
		create: _c,
	}
}

// AuthSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthSession nodes.
type AuthSessionUpsertBulk struct {
	create *AuthSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authsession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthSessionUpsertBulk) UpdateNewValues() *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authsession.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authsession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthSessionUpsertBulk) Ignore() *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthSessionUpsertBulk) DoNothing() *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthSessionCreateBulk.OnConflict
// documentation for more info.
func (u *AuthSessionUpsertBulk) Update(set func(*AuthSessionUpsert)) *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthSessionUpsertBulk) SetUpdatedAt(v time.Time) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateUpdatedAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthSessionUpsertBulk) SetSubjectID(v uuid.UUID) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateSubjectID() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateSubjectID()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthSessionUpsertBulk) SetLegacyUserID(v int64) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthSessionUpsertBulk) AddLegacyUserID(v int64) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateLegacyUserID() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetStatus sets the "status" field.
func (u *AuthSessionUpsertBulk) SetStatus(v string) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateStatus() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetAmr sets the "amr" field.
func (u *AuthSessionUpsertBulk) SetAmr(v string) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetAmr(v)
	})
}

// UpdateAmr sets the "amr" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateAmr() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateAmr()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AuthSessionUpsertBulk) SetLastSeenAt(v time.Time) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateLastSeenAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AuthSessionUpsertBulk) SetExpiresAt(v time.Time) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateExpiresAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAbsoluteExpiresAt sets the "absolute_expires_at" field.
func (u *AuthSessionUpsertBulk) SetAbsoluteExpiresAt(v time.Time) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetAbsoluteExpiresAt(v)
	})
}

// UpdateAbsoluteExpiresAt sets the "absolute_expires_at" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateAbsoluteExpiresAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateAbsoluteExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthSessionUpsertBulk) SetRevokedAt(v time.Time) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateRevokedAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthSessionUpsertBulk) ClearRevokedAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// SetCurrentRefreshTokenHash sets the "current_refresh_token_hash" field.
func (u *AuthSessionUpsertBulk) SetCurrentRefreshTokenHash(v string) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetCurrentRefreshTokenHash(v)
	})
}

// UpdateCurrentRefreshTokenHash sets the "current_refresh_token_hash" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateCurrentRefreshTokenHash() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateCurrentRefreshTokenHash()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *AuthSessionUpsertBulk) SetAuthVersion(v int64) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *AuthSessionUpsertBulk) AddAuthVersion(v int64) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateAuthVersion() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateAuthVersion()
	})
}

// Exec executes the query.
func (u *AuthSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
