// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authsubject"
	"github.com/google/uuid"
)

// AuthSubjectCreate is the builder for creating a AuthSubject entity.
type AuthSubjectCreate struct {
	config
	mutation *AuthSubjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthSubjectCreate) SetCreatedAt(v time.Time) *AuthSubjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthSubjectCreate) SetNillableCreatedAt(v *time.Time) *AuthSubjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthSubjectCreate) SetUpdatedAt(v time.Time) *AuthSubjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthSubjectCreate) SetNillableUpdatedAt(v *time.Time) *AuthSubjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_c *AuthSubjectCreate) SetLegacyUserID(v int64) *AuthSubjectCreate {
	_c.mutation.SetLegacyUserID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AuthSubjectCreate) SetEmail(v string) *AuthSubjectCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AuthSubjectCreate) SetStatus(v string) *AuthSubjectCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AuthSubjectCreate) SetNillableStatus(v *string) *AuthSubjectCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAuthVersion sets the "auth_version" field.
func (_c *AuthSubjectCreate) SetAuthVersion(v int64) *AuthSubjectCreate {
	_c.mutation.SetAuthVersion(v)
	return _c
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_c *AuthSubjectCreate) SetNillableAuthVersion(v *int64) *AuthSubjectCreate {
	if v != nil {
		_c.SetAuthVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthSubjectCreate) SetID(v uuid.UUID) *AuthSubjectCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuthSubjectCreate) SetNillableID(v *uuid.UUID) *AuthSubjectCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AuthSubjectMutation object of the builder.
func (_c *AuthSubjectCreate) Mutation() *AuthSubjectMutation {
	return _c.mutation
}

// Save creates the AuthSubject in the database.
func (_c *AuthSubjectCreate) Save(ctx context.Context) (*AuthSubject, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthSubjectCreate) SaveX(ctx context.Context) *AuthSubject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSubjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSubjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthSubjectCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authsubject.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authsubject.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := authsubject.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AuthVersion(); !ok {
		v := authsubject.DefaultAuthVersion
		_c.mutation.SetAuthVersion(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := authsubject.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthSubjectCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthSubject.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthSubject.updated_at"`)}
	}
	if _, ok := _c.mutation.LegacyUserID(); !ok {
		return &ValidationError{Name: "legacy_user_id", err: errors.New(`ent: missing required field "AuthSubject.legacy_user_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AuthSubject.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := authsubject.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthSubject.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AuthSubject.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := authsubject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuthSubject.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthVersion(); !ok {
		return &ValidationError{Name: "auth_version", err: errors.New(`ent: missing required field "AuthSubject.auth_version"`)}
	}
	return nil
}

func (_c *AuthSubjectCreate) sqlSave(ctx context.Context) (*AuthSubject, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthSubjectCreate) createSpec() (*AuthSubject, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthSubject{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authsubject.Table, sqlgraph.NewFieldSpec(authsubject.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authsubject.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authsubject.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LegacyUserID(); ok {
		_spec.SetField(authsubject.FieldLegacyUserID, field.TypeInt64, value)
		_node.LegacyUserID = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(authsubject.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(authsubject.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AuthVersion(); ok {
		_spec.SetField(authsubject.FieldAuthVersion, field.TypeInt64, value)
		_node.AuthVersion = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthSubject.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthSubjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthSubjectCreate) OnConflict(opts ...sql.ConflictOption) *AuthSubjectUpsertOne {
	_c.conflict = opts
	return &AuthSubjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthSubject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthSubjectCreate) OnConflictColumns(columns ...string) *AuthSubjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthSubjectUpsertOne{
		create: _c,
	}
}

type (
	// AuthSubjectUpsertOne is the builder for "upsert"-ing
	//  one AuthSubject node.
	AuthSubjectUpsertOne struct {
		create *AuthSubjectCreate
	}

	// AuthSubjectUpsert is the "OnConflict" setter.
	AuthSubjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthSubjectUpsert) SetUpdatedAt(v time.Time) *AuthSubjectUpsert {
	u.Set(authsubject.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthSubjectUpsert) UpdateUpdatedAt() *AuthSubjectUpsert {
	u.SetExcluded(authsubject.FieldUpdatedAt)
	return u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthSubjectUpsert) SetLegacyUserID(v int64) *AuthSubjectUpsert {
	u.Set(authsubject.FieldLegacyUserID, v)
	return u
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthSubjectUpsert) UpdateLegacyUserID() *AuthSubjectUpsert {
	u.SetExcluded(authsubject.FieldLegacyUserID)
	return u
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthSubjectUpsert) AddLegacyUserID(v int64) *AuthSubjectUpsert {
	u.Add(authsubject.FieldLegacyUserID, v)
	return u
}

// SetEmail sets the "email" field.
func (u *AuthSubjectUpsert) SetEmail(v string) *AuthSubjectUpsert {
	u.Set(authsubject.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthSubjectUpsert) UpdateEmail() *AuthSubjectUpsert {
	u.SetExcluded(authsubject.FieldEmail)
	return u
}

// SetStatus sets the "status" field.
func (u *AuthSubjectUpsert) SetStatus(v string) *AuthSubjectUpsert {
	u.Set(authsubject.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AuthSubjectUpsert) UpdateStatus() *AuthSubjectUpsert {
	u.SetExcluded(authsubject.FieldStatus)
	return u
}

// SetAuthVersion sets the "auth_version" field.
func (u *AuthSubjectUpsert) SetAuthVersion(v int64) *AuthSubjectUpsert {
	u.Set(authsubject.FieldAuthVersion, v)
	return u
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *AuthSubjectUpsert) UpdateAuthVersion() *AuthSubjectUpsert {
	u.SetExcluded(authsubject.FieldAuthVersion)
	return u
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *AuthSubjectUpsert) AddAuthVersion(v int64) *AuthSubjectUpsert {
	u.Add(authsubject.FieldAuthVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthSubject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authsubject.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthSubjectUpsertOne) UpdateNewValues() *AuthSubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authsubject.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authsubject.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthSubject.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthSubjectUpsertOne) Ignore() *AuthSubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthSubjectUpsertOne) DoNothing() *AuthSubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthSubjectCreate.OnConflict
// documentation for more info.
func (u *AuthSubjectUpsertOne) Update(set func(*AuthSubjectUpsert)) *AuthSubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthSubjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthSubjectUpsertOne) SetUpdatedAt(v time.Time) *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthSubjectUpsertOne) UpdateUpdatedAt() *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthSubjectUpsertOne) SetLegacyUserID(v int64) *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthSubjectUpsertOne) AddLegacyUserID(v int64) *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthSubjectUpsertOne) UpdateLegacyUserID() *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetEmail sets the "email" field.
func (u *AuthSubjectUpsertOne) SetEmail(v string) *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthSubjectUpsertOne) UpdateEmail() *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateEmail()
	})
}

// SetStatus sets the "status" field.
func (u *AuthSubjectUpsertOne) SetStatus(v string) *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AuthSubjectUpsertOne) UpdateStatus() *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *AuthSubjectUpsertOne) SetAuthVersion(v int64) *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *AuthSubjectUpsertOne) AddAuthVersion(v int64) *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *AuthSubjectUpsertOne) UpdateAuthVersion() *AuthSubjectUpsertOne {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateAuthVersion()
	})
}

// Exec executes the query.
func (u *AuthSubjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthSubjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthSubjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthSubjectUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthSubjectUpsertOne.ID is not supported by MySQL driver. Use AuthSubjectUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthSubjectUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthSubjectCreateBulk is the builder for creating many AuthSubject entities in bulk.
type AuthSubjectCreateBulk struct {
	config
	err      error
	builders []*AuthSubjectCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthSubject entities in the database.
func (_c *AuthSubjectCreateBulk) Save(ctx context.Context) ([]*AuthSubject, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthSubject, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthSubjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthSubjectCreateBulk) SaveX(ctx context.Context) []*AuthSubject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSubjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSubjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthSubject.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthSubjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthSubjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthSubjectUpsertBulk {
	_c.conflict = opts
	return &AuthSubjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthSubject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthSubjectCreateBulk) OnConflictColumns(columns ...string) *AuthSubjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthSubjectUpsertBulk{
		create: _c,
	}
}

// AuthSubjectUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthSubject nodes.
type AuthSubjectUpsertBulk struct {
	create *AuthSubjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthSubject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authsubject.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthSubjectUpsertBulk) UpdateNewValues() *AuthSubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authsubject.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authsubject.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthSubject.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthSubjectUpsertBulk) Ignore() *AuthSubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthSubjectUpsertBulk) DoNothing() *AuthSubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthSubjectCreateBulk.OnConflict
// documentation for more info.
func (u *AuthSubjectUpsertBulk) Update(set func(*AuthSubjectUpsert)) *AuthSubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthSubjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthSubjectUpsertBulk) SetUpdatedAt(v time.Time) *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthSubjectUpsertBulk) UpdateUpdatedAt() *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *AuthSubjectUpsertBulk) SetLegacyUserID(v int64) *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *AuthSubjectUpsertBulk) AddLegacyUserID(v int64) *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *AuthSubjectUpsertBulk) UpdateLegacyUserID() *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetEmail sets the "email" field.
func (u *AuthSubjectUpsertBulk) SetEmail(v string) *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthSubjectUpsertBulk) UpdateEmail() *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateEmail()
	})
}

// SetStatus sets the "status" field.
func (u *AuthSubjectUpsertBulk) SetStatus(v string) *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AuthSubjectUpsertBulk) UpdateStatus() *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthVersion sets the "auth_version" field.
func (u *AuthSubjectUpsertBulk) SetAuthVersion(v int64) *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.SetAuthVersion(v)
	})
}

// AddAuthVersion adds v to the "auth_version" field.
func (u *AuthSubjectUpsertBulk) AddAuthVersion(v int64) *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.AddAuthVersion(v)
	})
}

// UpdateAuthVersion sets the "auth_version" field to the value that was provided on create.
func (u *AuthSubjectUpsertBulk) UpdateAuthVersion() *AuthSubjectUpsertBulk {
	return u.Update(func(s *AuthSubjectUpsert) {
		s.UpdateAuthVersion()
	})
}

// Exec executes the query.
func (u *AuthSubjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthSubjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthSubjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthSubjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
