// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authsubject"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AuthSubjectUpdate is the builder for updating AuthSubject entities.
type AuthSubjectUpdate struct {
	config
	hooks    []Hook
	mutation *AuthSubjectMutation
}

// Where appends a list predicates to the AuthSubjectUpdate builder.
func (_u *AuthSubjectUpdate) Where(ps ...predicate.AuthSubject) *AuthSubjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthSubjectUpdate) SetUpdatedAt(v time.Time) *AuthSubjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_u *AuthSubjectUpdate) SetLegacyUserID(v int64) *AuthSubjectUpdate {
	_u.mutation.ResetLegacyUserID()
	_u.mutation.SetLegacyUserID(v)
	return _u
}

// SetNillableLegacyUserID sets the "legacy_user_id" field if the given value is not nil.
func (_u *AuthSubjectUpdate) SetNillableLegacyUserID(v *int64) *AuthSubjectUpdate {
	if v != nil {
		_u.SetLegacyUserID(*v)
	}
	return _u
}

// AddLegacyUserID adds value to the "legacy_user_id" field.
func (_u *AuthSubjectUpdate) AddLegacyUserID(v int64) *AuthSubjectUpdate {
	_u.mutation.AddLegacyUserID(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *AuthSubjectUpdate) SetEmail(v string) *AuthSubjectUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthSubjectUpdate) SetNillableEmail(v *string) *AuthSubjectUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AuthSubjectUpdate) SetStatus(v string) *AuthSubjectUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuthSubjectUpdate) SetNillableStatus(v *string) *AuthSubjectUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthVersion sets the "auth_version" field.
func (_u *AuthSubjectUpdate) SetAuthVersion(v int64) *AuthSubjectUpdate {
	_u.mutation.ResetAuthVersion()
	_u.mutation.SetAuthVersion(v)
	return _u
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_u *AuthSubjectUpdate) SetNillableAuthVersion(v *int64) *AuthSubjectUpdate {
	if v != nil {
		_u.SetAuthVersion(*v)
	}
	return _u
}

// AddAuthVersion adds value to the "auth_version" field.
func (_u *AuthSubjectUpdate) AddAuthVersion(v int64) *AuthSubjectUpdate {
	_u.mutation.AddAuthVersion(v)
	return _u
}

// Mutation returns the AuthSubjectMutation object of the builder.
func (_u *AuthSubjectUpdate) Mutation() *AuthSubjectMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthSubjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSubjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthSubjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSubjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthSubjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authsubject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthSubjectUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := authsubject.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthSubject.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := authsubject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuthSubject.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthSubjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authsubject.Table, authsubject.Columns, sqlgraph.NewFieldSpec(authsubject.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authsubject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LegacyUserID(); ok {
		_spec.SetField(authsubject.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLegacyUserID(); ok {
		_spec.AddField(authsubject.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authsubject.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(authsubject.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthVersion(); ok {
		_spec.SetField(authsubject.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthVersion(); ok {
		_spec.AddField(authsubject.FieldAuthVersion, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsubject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthSubjectUpdateOne is the builder for updating a single AuthSubject entity.
type AuthSubjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthSubjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthSubjectUpdateOne) SetUpdatedAt(v time.Time) *AuthSubjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_u *AuthSubjectUpdateOne) SetLegacyUserID(v int64) *AuthSubjectUpdateOne {
	_u.mutation.ResetLegacyUserID()
	_u.mutation.SetLegacyUserID(v)
	return _u
}

// SetNillableLegacyUserID sets the "legacy_user_id" field if the given value is not nil.
func (_u *AuthSubjectUpdateOne) SetNillableLegacyUserID(v *int64) *AuthSubjectUpdateOne {
	if v != nil {
		_u.SetLegacyUserID(*v)
	}
	return _u
}

// AddLegacyUserID adds value to the "legacy_user_id" field.
func (_u *AuthSubjectUpdateOne) AddLegacyUserID(v int64) *AuthSubjectUpdateOne {
	_u.mutation.AddLegacyUserID(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *AuthSubjectUpdateOne) SetEmail(v string) *AuthSubjectUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthSubjectUpdateOne) SetNillableEmail(v *string) *AuthSubjectUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AuthSubjectUpdateOne) SetStatus(v string) *AuthSubjectUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuthSubjectUpdateOne) SetNillableStatus(v *string) *AuthSubjectUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthVersion sets the "auth_version" field.
func (_u *AuthSubjectUpdateOne) SetAuthVersion(v int64) *AuthSubjectUpdateOne {
	_u.mutation.ResetAuthVersion()
	_u.mutation.SetAuthVersion(v)
	return _u
}

// SetNillableAuthVersion sets the "auth_version" field if the given value is not nil.
func (_u *AuthSubjectUpdateOne) SetNillableAuthVersion(v *int64) *AuthSubjectUpdateOne {
	if v != nil {
		_u.SetAuthVersion(*v)
	}
	return _u
}

// AddAuthVersion adds value to the "auth_version" field.
func (_u *AuthSubjectUpdateOne) AddAuthVersion(v int64) *AuthSubjectUpdateOne {
	_u.mutation.AddAuthVersion(v)
	return _u
}

// Mutation returns the AuthSubjectMutation object of the builder.
func (_u *AuthSubjectUpdateOne) Mutation() *AuthSubjectMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthSubjectUpdate builder.
func (_u *AuthSubjectUpdateOne) Where(ps ...predicate.AuthSubject) *AuthSubjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthSubjectUpdateOne) Select(field string, fields ...string) *AuthSubjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthSubject entity.
func (_u *AuthSubjectUpdateOne) Save(ctx context.Context) (*AuthSubject, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSubjectUpdateOne) SaveX(ctx context.Context) *AuthSubject {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthSubjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSubjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthSubjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authsubject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthSubjectUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := authsubject.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthSubject.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := authsubject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuthSubject.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthSubjectUpdateOne) sqlSave(ctx context.Context) (_node *AuthSubject, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authsubject.Table, authsubject.Columns, sqlgraph.NewFieldSpec(authsubject.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthSubject.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authsubject.FieldID)
		for _, f := range fields {
			if !authsubject.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authsubject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authsubject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LegacyUserID(); ok {
		_spec.SetField(authsubject.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLegacyUserID(); ok {
		_spec.AddField(authsubject.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authsubject.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(authsubject.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthVersion(); ok {
		_spec.SetField(authsubject.FieldAuthVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthVersion(); ok {
		_spec.AddField(authsubject.FieldAuthVersion, field.TypeInt64, value)
	}
	_node = &AuthSubject{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsubject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
