// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authfederatedidentity"
	"github.com/google/uuid"
)

// AuthFederatedIdentityCreate is the builder for creating a AuthFederatedIdentity entity.
type AuthFederatedIdentityCreate struct {
	config
	mutation *AuthFederatedIdentityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthFederatedIdentityCreate) SetCreatedAt(v time.Time) *AuthFederatedIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthFederatedIdentityCreate) SetNillableCreatedAt(v *time.Time) *AuthFederatedIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthFederatedIdentityCreate) SetUpdatedAt(v time.Time) *AuthFederatedIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthFederatedIdentityCreate) SetNillableUpdatedAt(v *time.Time) *AuthFederatedIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *AuthFederatedIdentityCreate) SetSubjectID(v uuid.UUID) *AuthFederatedIdentityCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AuthFederatedIdentityCreate) SetProvider(v string) *AuthFederatedIdentityCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *AuthFederatedIdentityCreate) SetIssuer(v string) *AuthFederatedIdentityCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetExternalSubject sets the "external_subject" field.
func (_c *AuthFederatedIdentityCreate) SetExternalSubject(v string) *AuthFederatedIdentityCreate {
	_c.mutation.SetExternalSubject(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AuthFederatedIdentityCreate) SetEmail(v string) *AuthFederatedIdentityCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *AuthFederatedIdentityCreate) SetNillableEmail(v *string) *AuthFederatedIdentityCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *AuthFederatedIdentityCreate) SetUsername(v string) *AuthFederatedIdentityCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *AuthFederatedIdentityCreate) SetNillableUsername(v *string) *AuthFederatedIdentityCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthFederatedIdentityCreate) SetID(v int64) *AuthFederatedIdentityCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthFederatedIdentityMutation object of the builder.
func (_c *AuthFederatedIdentityCreate) Mutation() *AuthFederatedIdentityMutation {
	return _c.mutation
}

// Save creates the AuthFederatedIdentity in the database.
func (_c *AuthFederatedIdentityCreate) Save(ctx context.Context) (*AuthFederatedIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthFederatedIdentityCreate) SaveX(ctx context.Context) *AuthFederatedIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthFederatedIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthFederatedIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthFederatedIdentityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authfederatedidentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authfederatedidentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := authfederatedidentity.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := authfederatedidentity.DefaultUsername
		_c.mutation.SetUsername(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthFederatedIdentityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthFederatedIdentity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthFederatedIdentity.updated_at"`)}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "AuthFederatedIdentity.subject_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AuthFederatedIdentity.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := authfederatedidentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AuthFederatedIdentity.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "AuthFederatedIdentity.issuer"`)}
	}
	if v, ok := _c.mutation.Issuer(); ok {
		if err := authfederatedidentity.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "AuthFederatedIdentity.issuer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalSubject(); !ok {
		return &ValidationError{Name: "external_subject", err: errors.New(`ent: missing required field "AuthFederatedIdentity.external_subject"`)}
	}
	if v, ok := _c.mutation.ExternalSubject(); ok {
		if err := authfederatedidentity.ExternalSubjectValidator(v); err != nil {
			return &ValidationError{Name: "external_subject", err: fmt.Errorf(`ent: validator failed for field "AuthFederatedIdentity.external_subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AuthFederatedIdentity.email"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AuthFederatedIdentity.username"`)}
	}
	return nil
}

func (_c *AuthFederatedIdentityCreate) sqlSave(ctx context.Context) (*AuthFederatedIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthFederatedIdentityCreate) createSpec() (*AuthFederatedIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthFederatedIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authfederatedidentity.Table, sqlgraph.NewFieldSpec(authfederatedidentity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authfederatedidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authfederatedidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(authfederatedidentity.FieldSubjectID, field.TypeUUID, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(authfederatedidentity.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(authfederatedidentity.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.ExternalSubject(); ok {
		_spec.SetField(authfederatedidentity.FieldExternalSubject, field.TypeString, value)
		_node.ExternalSubject = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(authfederatedidentity.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(authfederatedidentity.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthFederatedIdentity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthFederatedIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthFederatedIdentityCreate) OnConflict(opts ...sql.ConflictOption) *AuthFederatedIdentityUpsertOne {
	_c.conflict = opts
	return &AuthFederatedIdentityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthFederatedIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthFederatedIdentityCreate) OnConflictColumns(columns ...string) *AuthFederatedIdentityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthFederatedIdentityUpsertOne{
		create: _c,
	}
}

type (
	// AuthFederatedIdentityUpsertOne is the builder for "upsert"-ing
	//  one AuthFederatedIdentity node.
	AuthFederatedIdentityUpsertOne struct {
		create *AuthFederatedIdentityCreate
	}

	// AuthFederatedIdentityUpsert is the "OnConflict" setter.
	AuthFederatedIdentityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthFederatedIdentityUpsert) SetUpdatedAt(v time.Time) *AuthFederatedIdentityUpsert {
	u.Set(authfederatedidentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsert) UpdateUpdatedAt() *AuthFederatedIdentityUpsert {
	u.SetExcluded(authfederatedidentity.FieldUpdatedAt)
	return u
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthFederatedIdentityUpsert) SetSubjectID(v uuid.UUID) *AuthFederatedIdentityUpsert {
	u.Set(authfederatedidentity.FieldSubjectID, v)
	return u
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsert) UpdateSubjectID() *AuthFederatedIdentityUpsert {
	u.SetExcluded(authfederatedidentity.FieldSubjectID)
	return u
}

// SetProvider sets the "provider" field.
func (u *AuthFederatedIdentityUpsert) SetProvider(v string) *AuthFederatedIdentityUpsert {
	u.Set(authfederatedidentity.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsert) UpdateProvider() *AuthFederatedIdentityUpsert {
	u.SetExcluded(authfederatedidentity.FieldProvider)
	return u
}

// SetIssuer sets the "issuer" field.
func (u *AuthFederatedIdentityUpsert) SetIssuer(v string) *AuthFederatedIdentityUpsert {
	u.Set(authfederatedidentity.FieldIssuer, v)
	return u
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsert) UpdateIssuer() *AuthFederatedIdentityUpsert {
	u.SetExcluded(authfederatedidentity.FieldIssuer)
	return u
}

// SetExternalSubject sets the "external_subject" field.
func (u *AuthFederatedIdentityUpsert) SetExternalSubject(v string) *AuthFederatedIdentityUpsert {
	u.Set(authfederatedidentity.FieldExternalSubject, v)
	return u
}

// UpdateExternalSubject sets the "external_subject" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsert) UpdateExternalSubject() *AuthFederatedIdentityUpsert {
	u.SetExcluded(authfederatedidentity.FieldExternalSubject)
	return u
}

// SetEmail sets the "email" field.
func (u *AuthFederatedIdentityUpsert) SetEmail(v string) *AuthFederatedIdentityUpsert {
	u.Set(authfederatedidentity.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsert) UpdateEmail() *AuthFederatedIdentityUpsert {
	u.SetExcluded(authfederatedidentity.FieldEmail)
	return u
}

// SetUsername sets the "username" field.
func (u *AuthFederatedIdentityUpsert) SetUsername(v string) *AuthFederatedIdentityUpsert {
	u.Set(authfederatedidentity.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsert) UpdateUsername() *AuthFederatedIdentityUpsert {
	u.SetExcluded(authfederatedidentity.FieldUsername)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthFederatedIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authfederatedidentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthFederatedIdentityUpsertOne) UpdateNewValues() *AuthFederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authfederatedidentity.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authfederatedidentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthFederatedIdentity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthFederatedIdentityUpsertOne) Ignore() *AuthFederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthFederatedIdentityUpsertOne) DoNothing() *AuthFederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthFederatedIdentityCreate.OnConflict
// documentation for more info.
func (u *AuthFederatedIdentityUpsertOne) Update(set func(*AuthFederatedIdentityUpsert)) *AuthFederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthFederatedIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthFederatedIdentityUpsertOne) SetUpdatedAt(v time.Time) *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertOne) UpdateUpdatedAt() *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthFederatedIdentityUpsertOne) SetSubjectID(v uuid.UUID) *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertOne) UpdateSubjectID() *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateSubjectID()
	})
}

// SetProvider sets the "provider" field.
func (u *AuthFederatedIdentityUpsertOne) SetProvider(v string) *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertOne) UpdateProvider() *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetIssuer sets the "issuer" field.
func (u *AuthFederatedIdentityUpsertOne) SetIssuer(v string) *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertOne) UpdateIssuer() *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateIssuer()
	})
}

// SetExternalSubject sets the "external_subject" field.
func (u *AuthFederatedIdentityUpsertOne) SetExternalSubject(v string) *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetExternalSubject(v)
	})
}

// UpdateExternalSubject sets the "external_subject" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertOne) UpdateExternalSubject() *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateExternalSubject()
	})
}

// SetEmail sets the "email" field.
func (u *AuthFederatedIdentityUpsertOne) SetEmail(v string) *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertOne) UpdateEmail() *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateEmail()
	})
}

// SetUsername sets the "username" field.
func (u *AuthFederatedIdentityUpsertOne) SetUsername(v string) *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertOne) UpdateUsername() *AuthFederatedIdentityUpsertOne {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateUsername()
	})
}

// Exec executes the query.
func (u *AuthFederatedIdentityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthFederatedIdentityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthFederatedIdentityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthFederatedIdentityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthFederatedIdentityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthFederatedIdentityCreateBulk is the builder for creating many AuthFederatedIdentity entities in bulk.
type AuthFederatedIdentityCreateBulk struct {
	config
	err      error
	builders []*AuthFederatedIdentityCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthFederatedIdentity entities in the database.
func (_c *AuthFederatedIdentityCreateBulk) Save(ctx context.Context) ([]*AuthFederatedIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthFederatedIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthFederatedIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthFederatedIdentityCreateBulk) SaveX(ctx context.Context) []*AuthFederatedIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthFederatedIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthFederatedIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthFederatedIdentity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthFederatedIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthFederatedIdentityCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthFederatedIdentityUpsertBulk {
	_c.conflict = opts
	return &AuthFederatedIdentityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthFederatedIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthFederatedIdentityCreateBulk) OnConflictColumns(columns ...string) *AuthFederatedIdentityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthFederatedIdentityUpsertBulk{
		create: _c,
	}
}

// AuthFederatedIdentityUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthFederatedIdentity nodes.
type AuthFederatedIdentityUpsertBulk struct {
	create *AuthFederatedIdentityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthFederatedIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authfederatedidentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthFederatedIdentityUpsertBulk) UpdateNewValues() *AuthFederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authfederatedidentity.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authfederatedidentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthFederatedIdentity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthFederatedIdentityUpsertBulk) Ignore() *AuthFederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthFederatedIdentityUpsertBulk) DoNothing() *AuthFederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthFederatedIdentityCreateBulk.OnConflict
// documentation for more info.
func (u *AuthFederatedIdentityUpsertBulk) Update(set func(*AuthFederatedIdentityUpsert)) *AuthFederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthFederatedIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthFederatedIdentityUpsertBulk) SetUpdatedAt(v time.Time) *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertBulk) UpdateUpdatedAt() *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *AuthFederatedIdentityUpsertBulk) SetSubjectID(v uuid.UUID) *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertBulk) UpdateSubjectID() *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateSubjectID()
	})
}

// SetProvider sets the "provider" field.
func (u *AuthFederatedIdentityUpsertBulk) SetProvider(v string) *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertBulk) UpdateProvider() *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetIssuer sets the "issuer" field.
func (u *AuthFederatedIdentityUpsertBulk) SetIssuer(v string) *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertBulk) UpdateIssuer() *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateIssuer()
	})
}

// SetExternalSubject sets the "external_subject" field.
func (u *AuthFederatedIdentityUpsertBulk) SetExternalSubject(v string) *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetExternalSubject(v)
	})
}

// UpdateExternalSubject sets the "external_subject" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertBulk) UpdateExternalSubject() *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateExternalSubject()
	})
}

// SetEmail sets the "email" field.
func (u *AuthFederatedIdentityUpsertBulk) SetEmail(v string) *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertBulk) UpdateEmail() *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateEmail()
	})
}

// SetUsername sets the "username" field.
func (u *AuthFederatedIdentityUpsertBulk) SetUsername(v string) *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthFederatedIdentityUpsertBulk) UpdateUsername() *AuthFederatedIdentityUpsertBulk {
	return u.Update(func(s *AuthFederatedIdentityUpsert) {
		s.UpdateUsername()
	})
}

// Exec executes the query.
func (u *AuthFederatedIdentityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthFederatedIdentityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthFederatedIdentityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthFederatedIdentityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
