// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/authsubject"
	"github.com/google/uuid"
)

// AuthSubject is the model entity for the AuthSubject schema.
type AuthSubject struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LegacyUserID holds the value of the "legacy_user_id" field.
	LegacyUserID int64 `json:"legacy_user_id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AuthVersion holds the value of the "auth_version" field.
	AuthVersion  int64 `json:"auth_version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthSubject) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authsubject.FieldLegacyUserID, authsubject.FieldAuthVersion:
			values[i] = new(sql.NullInt64)
		case authsubject.FieldEmail, authsubject.FieldStatus:
			values[i] = new(sql.NullString)
		case authsubject.FieldCreatedAt, authsubject.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case authsubject.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthSubject fields.
func (_m *AuthSubject) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authsubject.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case authsubject.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case authsubject.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case authsubject.FieldLegacyUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field legacy_user_id", values[i])
			} else if value.Valid {
				_m.LegacyUserID = value.Int64
			}
		case authsubject.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case authsubject.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case authsubject.FieldAuthVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auth_version", values[i])
			} else if value.Valid {
				_m.AuthVersion = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthSubject.
// This includes values selected through modifiers, order, etc.
func (_m *AuthSubject) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuthSubject.
// Note that you need to call AuthSubject.Unwrap() before calling this method if this AuthSubject
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthSubject) Update() *AuthSubjectUpdateOne {
	return NewAuthSubjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthSubject entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthSubject) Unwrap() *AuthSubject {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthSubject is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthSubject) String() string {
	var builder strings.Builder
	builder.WriteString("AuthSubject(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("legacy_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LegacyUserID))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("auth_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthVersion))
	builder.WriteByte(')')
	return builder.String()
}

// AuthSubjects is a parsable slice of AuthSubject.
type AuthSubjects []*AuthSubject
