// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/authrefreshtoken"
	"github.com/google/uuid"
)

// AuthRefreshToken is the model entity for the AuthRefreshToken schema.
type AuthRefreshToken struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Sid holds the value of the "sid" field.
	Sid uuid.UUID `json:"sid,omitempty"`
	// SubjectID holds the value of the "subject_id" field.
	SubjectID uuid.UUID `json:"subject_id,omitempty"`
	// LegacyUserID holds the value of the "legacy_user_id" field.
	LegacyUserID int64 `json:"legacy_user_id,omitempty"`
	// IdleExpiresAt holds the value of the "idle_expires_at" field.
	IdleExpiresAt time.Time `json:"idle_expires_at,omitempty"`
	// AbsoluteExpiresAt holds the value of the "absolute_expires_at" field.
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at,omitempty"`
	// RotatedAt holds the value of the "rotated_at" field.
	RotatedAt *time.Time `json:"rotated_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// ReplacedByTokenHash holds the value of the "replaced_by_token_hash" field.
	ReplacedByTokenHash *string `json:"-"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthRefreshToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authrefreshtoken.FieldLegacyUserID:
			values[i] = new(sql.NullInt64)
		case authrefreshtoken.FieldID, authrefreshtoken.FieldReplacedByTokenHash:
			values[i] = new(sql.NullString)
		case authrefreshtoken.FieldCreatedAt, authrefreshtoken.FieldUpdatedAt, authrefreshtoken.FieldIdleExpiresAt, authrefreshtoken.FieldAbsoluteExpiresAt, authrefreshtoken.FieldRotatedAt, authrefreshtoken.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case authrefreshtoken.FieldSid, authrefreshtoken.FieldSubjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthRefreshToken fields.
func (_m *AuthRefreshToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authrefreshtoken.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case authrefreshtoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case authrefreshtoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case authrefreshtoken.FieldSid:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field sid", values[i])
			} else if value != nil {
				_m.Sid = *value
			}
		case authrefreshtoken.FieldSubjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field subject_id", values[i])
			} else if value != nil {
				_m.SubjectID = *value
			}
		case authrefreshtoken.FieldLegacyUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field legacy_user_id", values[i])
			} else if value.Valid {
				_m.LegacyUserID = value.Int64
			}
		case authrefreshtoken.FieldIdleExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field idle_expires_at", values[i])
			} else if value.Valid {
				_m.IdleExpiresAt = value.Time
			}
		case authrefreshtoken.FieldAbsoluteExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field absolute_expires_at", values[i])
			} else if value.Valid {
				_m.AbsoluteExpiresAt = value.Time
			}
		case authrefreshtoken.FieldRotatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rotated_at", values[i])
			} else if value.Valid {
				_m.RotatedAt = new(time.Time)
				*_m.RotatedAt = value.Time
			}
		case authrefreshtoken.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case authrefreshtoken.FieldReplacedByTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replaced_by_token_hash", values[i])
			} else if value.Valid {
				_m.ReplacedByTokenHash = new(string)
				*_m.ReplacedByTokenHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthRefreshToken.
// This includes values selected through modifiers, order, etc.
func (_m *AuthRefreshToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuthRefreshToken.
// Note that you need to call AuthRefreshToken.Unwrap() before calling this method if this AuthRefreshToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthRefreshToken) Update() *AuthRefreshTokenUpdateOne {
	return NewAuthRefreshTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthRefreshToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthRefreshToken) Unwrap() *AuthRefreshToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthRefreshToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthRefreshToken) String() string {
	var builder strings.Builder
	builder.WriteString("AuthRefreshToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sid))
	builder.WriteString(", ")
	builder.WriteString("subject_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubjectID))
	builder.WriteString(", ")
	builder.WriteString("legacy_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LegacyUserID))
	builder.WriteString(", ")
	builder.WriteString("idle_expires_at=")
	builder.WriteString(_m.IdleExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("absolute_expires_at=")
	builder.WriteString(_m.AbsoluteExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RotatedAt; v != nil {
		builder.WriteString("rotated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("replaced_by_token_hash=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// AuthRefreshTokens is a parsable slice of AuthRefreshToken.
type AuthRefreshTokens []*AuthRefreshToken
