// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/authfederatedidentity"
	"github.com/google/uuid"
)

// AuthFederatedIdentity is the model entity for the AuthFederatedIdentity schema.
type AuthFederatedIdentity struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SubjectID holds the value of the "subject_id" field.
	SubjectID uuid.UUID `json:"subject_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Issuer holds the value of the "issuer" field.
	Issuer string `json:"issuer,omitempty"`
	// ExternalSubject holds the value of the "external_subject" field.
	ExternalSubject string `json:"external_subject,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Username holds the value of the "username" field.
	Username     string `json:"username,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthFederatedIdentity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authfederatedidentity.FieldID:
			values[i] = new(sql.NullInt64)
		case authfederatedidentity.FieldProvider, authfederatedidentity.FieldIssuer, authfederatedidentity.FieldExternalSubject, authfederatedidentity.FieldEmail, authfederatedidentity.FieldUsername:
			values[i] = new(sql.NullString)
		case authfederatedidentity.FieldCreatedAt, authfederatedidentity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case authfederatedidentity.FieldSubjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthFederatedIdentity fields.
func (_m *AuthFederatedIdentity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authfederatedidentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case authfederatedidentity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case authfederatedidentity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case authfederatedidentity.FieldSubjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field subject_id", values[i])
			} else if value != nil {
				_m.SubjectID = *value
			}
		case authfederatedidentity.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case authfederatedidentity.FieldIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer", values[i])
			} else if value.Valid {
				_m.Issuer = value.String
			}
		case authfederatedidentity.FieldExternalSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_subject", values[i])
			} else if value.Valid {
				_m.ExternalSubject = value.String
			}
		case authfederatedidentity.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case authfederatedidentity.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthFederatedIdentity.
// This includes values selected through modifiers, order, etc.
func (_m *AuthFederatedIdentity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuthFederatedIdentity.
// Note that you need to call AuthFederatedIdentity.Unwrap() before calling this method if this AuthFederatedIdentity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthFederatedIdentity) Update() *AuthFederatedIdentityUpdateOne {
	return NewAuthFederatedIdentityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthFederatedIdentity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthFederatedIdentity) Unwrap() *AuthFederatedIdentity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthFederatedIdentity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthFederatedIdentity) String() string {
	var builder strings.Builder
	builder.WriteString("AuthFederatedIdentity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("subject_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubjectID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("issuer=")
	builder.WriteString(_m.Issuer)
	builder.WriteString(", ")
	builder.WriteString("external_subject=")
	builder.WriteString(_m.ExternalSubject)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteByte(')')
	return builder.String()
}

// AuthFederatedIdentities is a parsable slice of AuthFederatedIdentity.
type AuthFederatedIdentities []*AuthFederatedIdentity
