// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/authemailverification"
	"github.com/google/uuid"
)

// AuthEmailVerification is the model entity for the AuthEmailVerification schema.
type AuthEmailVerification struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SubjectID holds the value of the "subject_id" field.
	SubjectID *uuid.UUID `json:"subject_id,omitempty"`
	// Purpose holds the value of the "purpose" field.
	Purpose string `json:"purpose,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash string `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt   *time.Time `json:"consumed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthEmailVerification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authemailverification.FieldSubjectID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case authemailverification.FieldPurpose, authemailverification.FieldEmail, authemailverification.FieldCodeHash:
			values[i] = new(sql.NullString)
		case authemailverification.FieldCreatedAt, authemailverification.FieldUpdatedAt, authemailverification.FieldExpiresAt, authemailverification.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		case authemailverification.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthEmailVerification fields.
func (_m *AuthEmailVerification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authemailverification.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case authemailverification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case authemailverification.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case authemailverification.FieldSubjectID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field subject_id", values[i])
			} else if value.Valid {
				_m.SubjectID = new(uuid.UUID)
				*_m.SubjectID = *value.S.(*uuid.UUID)
			}
		case authemailverification.FieldPurpose:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purpose", values[i])
			} else if value.Valid {
				_m.Purpose = value.String
			}
		case authemailverification.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case authemailverification.FieldCodeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value.Valid {
				_m.CodeHash = value.String
			}
		case authemailverification.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case authemailverification.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthEmailVerification.
// This includes values selected through modifiers, order, etc.
func (_m *AuthEmailVerification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuthEmailVerification.
// Note that you need to call AuthEmailVerification.Unwrap() before calling this method if this AuthEmailVerification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthEmailVerification) Update() *AuthEmailVerificationUpdateOne {
	return NewAuthEmailVerificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthEmailVerification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthEmailVerification) Unwrap() *AuthEmailVerification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthEmailVerification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthEmailVerification) String() string {
	var builder strings.Builder
	builder.WriteString("AuthEmailVerification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SubjectID; v != nil {
		builder.WriteString("subject_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("purpose=")
	builder.WriteString(_m.Purpose)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("code_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AuthEmailVerifications is a parsable slice of AuthEmailVerification.
type AuthEmailVerifications []*AuthEmailVerification
