// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authpasswordcredential"
	"github.com/google/uuid"
)

// AuthPasswordCredentialCreate is the builder for creating a AuthPasswordCredential entity.
type AuthPasswordCredentialCreate struct {
	config
	mutation *AuthPasswordCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthPasswordCredentialCreate) SetCreatedAt(v time.Time) *AuthPasswordCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthPasswordCredentialCreate) SetNillableCreatedAt(v *time.Time) *AuthPasswordCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthPasswordCredentialCreate) SetUpdatedAt(v time.Time) *AuthPasswordCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthPasswordCredentialCreate) SetNillableUpdatedAt(v *time.Time) *AuthPasswordCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *AuthPasswordCredentialCreate) SetPasswordHash(v string) *AuthPasswordCredentialCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetChangedAt sets the "changed_at" field.
func (_c *AuthPasswordCredentialCreate) SetChangedAt(v time.Time) *AuthPasswordCredentialCreate {
	_c.mutation.SetChangedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AuthPasswordCredentialCreate) SetID(v uuid.UUID) *AuthPasswordCredentialCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthPasswordCredentialMutation object of the builder.
func (_c *AuthPasswordCredentialCreate) Mutation() *AuthPasswordCredentialMutation {
	return _c.mutation
}

// Save creates the AuthPasswordCredential in the database.
func (_c *AuthPasswordCredentialCreate) Save(ctx context.Context) (*AuthPasswordCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthPasswordCredentialCreate) SaveX(ctx context.Context) *AuthPasswordCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthPasswordCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthPasswordCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthPasswordCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authpasswordcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authpasswordcredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthPasswordCredentialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthPasswordCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthPasswordCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "AuthPasswordCredential.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := authpasswordcredential.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "AuthPasswordCredential.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChangedAt(); !ok {
		return &ValidationError{Name: "changed_at", err: errors.New(`ent: missing required field "AuthPasswordCredential.changed_at"`)}
	}
	return nil
}

func (_c *AuthPasswordCredentialCreate) sqlSave(ctx context.Context) (*AuthPasswordCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthPasswordCredentialCreate) createSpec() (*AuthPasswordCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthPasswordCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authpasswordcredential.Table, sqlgraph.NewFieldSpec(authpasswordcredential.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authpasswordcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authpasswordcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(authpasswordcredential.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.ChangedAt(); ok {
		_spec.SetField(authpasswordcredential.FieldChangedAt, field.TypeTime, value)
		_node.ChangedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthPasswordCredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthPasswordCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthPasswordCredentialCreate) OnConflict(opts ...sql.ConflictOption) *AuthPasswordCredentialUpsertOne {
	_c.conflict = opts
	return &AuthPasswordCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthPasswordCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthPasswordCredentialCreate) OnConflictColumns(columns ...string) *AuthPasswordCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthPasswordCredentialUpsertOne{
		create: _c,
	}
}

type (
	// AuthPasswordCredentialUpsertOne is the builder for "upsert"-ing
	//  one AuthPasswordCredential node.
	AuthPasswordCredentialUpsertOne struct {
		create *AuthPasswordCredentialCreate
	}

	// AuthPasswordCredentialUpsert is the "OnConflict" setter.
	AuthPasswordCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthPasswordCredentialUpsert) SetUpdatedAt(v time.Time) *AuthPasswordCredentialUpsert {
	u.Set(authpasswordcredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsert) UpdateUpdatedAt() *AuthPasswordCredentialUpsert {
	u.SetExcluded(authpasswordcredential.FieldUpdatedAt)
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *AuthPasswordCredentialUpsert) SetPasswordHash(v string) *AuthPasswordCredentialUpsert {
	u.Set(authpasswordcredential.FieldPasswordHash, v)
	return u
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsert) UpdatePasswordHash() *AuthPasswordCredentialUpsert {
	u.SetExcluded(authpasswordcredential.FieldPasswordHash)
	return u
}

// SetChangedAt sets the "changed_at" field.
func (u *AuthPasswordCredentialUpsert) SetChangedAt(v time.Time) *AuthPasswordCredentialUpsert {
	u.Set(authpasswordcredential.FieldChangedAt, v)
	return u
}

// UpdateChangedAt sets the "changed_at" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsert) UpdateChangedAt() *AuthPasswordCredentialUpsert {
	u.SetExcluded(authpasswordcredential.FieldChangedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthPasswordCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authpasswordcredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthPasswordCredentialUpsertOne) UpdateNewValues() *AuthPasswordCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authpasswordcredential.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authpasswordcredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthPasswordCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthPasswordCredentialUpsertOne) Ignore() *AuthPasswordCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthPasswordCredentialUpsertOne) DoNothing() *AuthPasswordCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthPasswordCredentialCreate.OnConflict
// documentation for more info.
func (u *AuthPasswordCredentialUpsertOne) Update(set func(*AuthPasswordCredentialUpsert)) *AuthPasswordCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthPasswordCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthPasswordCredentialUpsertOne) SetUpdatedAt(v time.Time) *AuthPasswordCredentialUpsertOne {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsertOne) UpdateUpdatedAt() *AuthPasswordCredentialUpsertOne {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *AuthPasswordCredentialUpsertOne) SetPasswordHash(v string) *AuthPasswordCredentialUpsertOne {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsertOne) UpdatePasswordHash() *AuthPasswordCredentialUpsertOne {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetChangedAt sets the "changed_at" field.
func (u *AuthPasswordCredentialUpsertOne) SetChangedAt(v time.Time) *AuthPasswordCredentialUpsertOne {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.SetChangedAt(v)
	})
}

// UpdateChangedAt sets the "changed_at" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsertOne) UpdateChangedAt() *AuthPasswordCredentialUpsertOne {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.UpdateChangedAt()
	})
}

// Exec executes the query.
func (u *AuthPasswordCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthPasswordCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthPasswordCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthPasswordCredentialUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthPasswordCredentialUpsertOne.ID is not supported by MySQL driver. Use AuthPasswordCredentialUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthPasswordCredentialUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthPasswordCredentialCreateBulk is the builder for creating many AuthPasswordCredential entities in bulk.
type AuthPasswordCredentialCreateBulk struct {
	config
	err      error
	builders []*AuthPasswordCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthPasswordCredential entities in the database.
func (_c *AuthPasswordCredentialCreateBulk) Save(ctx context.Context) ([]*AuthPasswordCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthPasswordCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthPasswordCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthPasswordCredentialCreateBulk) SaveX(ctx context.Context) []*AuthPasswordCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthPasswordCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthPasswordCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthPasswordCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthPasswordCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthPasswordCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthPasswordCredentialUpsertBulk {
	_c.conflict = opts
	return &AuthPasswordCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthPasswordCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthPasswordCredentialCreateBulk) OnConflictColumns(columns ...string) *AuthPasswordCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthPasswordCredentialUpsertBulk{
		create: _c,
	}
}

// AuthPasswordCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthPasswordCredential nodes.
type AuthPasswordCredentialUpsertBulk struct {
	create *AuthPasswordCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthPasswordCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authpasswordcredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthPasswordCredentialUpsertBulk) UpdateNewValues() *AuthPasswordCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authpasswordcredential.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authpasswordcredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthPasswordCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthPasswordCredentialUpsertBulk) Ignore() *AuthPasswordCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthPasswordCredentialUpsertBulk) DoNothing() *AuthPasswordCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthPasswordCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *AuthPasswordCredentialUpsertBulk) Update(set func(*AuthPasswordCredentialUpsert)) *AuthPasswordCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthPasswordCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthPasswordCredentialUpsertBulk) SetUpdatedAt(v time.Time) *AuthPasswordCredentialUpsertBulk {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsertBulk) UpdateUpdatedAt() *AuthPasswordCredentialUpsertBulk {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *AuthPasswordCredentialUpsertBulk) SetPasswordHash(v string) *AuthPasswordCredentialUpsertBulk {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsertBulk) UpdatePasswordHash() *AuthPasswordCredentialUpsertBulk {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetChangedAt sets the "changed_at" field.
func (u *AuthPasswordCredentialUpsertBulk) SetChangedAt(v time.Time) *AuthPasswordCredentialUpsertBulk {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.SetChangedAt(v)
	})
}

// UpdateChangedAt sets the "changed_at" field to the value that was provided on create.
func (u *AuthPasswordCredentialUpsertBulk) UpdateChangedAt() *AuthPasswordCredentialUpsertBulk {
	return u.Update(func(s *AuthPasswordCredentialUpsert) {
		s.UpdateChangedAt()
	})
}

// Exec executes the query.
func (u *AuthPasswordCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthPasswordCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthPasswordCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthPasswordCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
