// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authsubject"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AuthSubjectDelete is the builder for deleting a AuthSubject entity.
type AuthSubjectDelete struct {
	config
	hooks    []Hook
	mutation *AuthSubjectMutation
}

// Where appends a list predicates to the AuthSubjectDelete builder.
func (_d *AuthSubjectDelete) Where(ps ...predicate.AuthSubject) *AuthSubjectDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthSubjectDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthSubjectDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthSubjectDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authsubject.Table, sqlgraph.NewFieldSpec(authsubject.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthSubjectDeleteOne is the builder for deleting a single AuthSubject entity.
type AuthSubjectDeleteOne struct {
	_d *AuthSubjectDelete
}

// Where appends a list predicates to the AuthSubjectDelete builder.
func (_d *AuthSubjectDeleteOne) Where(ps ...predicate.AuthSubject) *AuthSubjectDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthSubjectDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authsubject.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthSubjectDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
