// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/controluserprofile"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ControlUserProfileUpdate is the builder for updating ControlUserProfile entities.
type ControlUserProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ControlUserProfileMutation
}

// Where appends a list predicates to the ControlUserProfileUpdate builder.
func (_u *ControlUserProfileUpdate) Where(ps ...predicate.ControlUserProfile) *ControlUserProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ControlUserProfileUpdate) SetUpdatedAt(v time.Time) *ControlUserProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_u *ControlUserProfileUpdate) SetLegacyUserID(v int64) *ControlUserProfileUpdate {
	_u.mutation.ResetLegacyUserID()
	_u.mutation.SetLegacyUserID(v)
	return _u
}

// SetNillableLegacyUserID sets the "legacy_user_id" field if the given value is not nil.
func (_u *ControlUserProfileUpdate) SetNillableLegacyUserID(v *int64) *ControlUserProfileUpdate {
	if v != nil {
		_u.SetLegacyUserID(*v)
	}
	return _u
}

// AddLegacyUserID adds value to the "legacy_user_id" field.
func (_u *ControlUserProfileUpdate) AddLegacyUserID(v int64) *ControlUserProfileUpdate {
	_u.mutation.AddLegacyUserID(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *ControlUserProfileUpdate) SetEmail(v string) *ControlUserProfileUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ControlUserProfileUpdate) SetNillableEmail(v *string) *ControlUserProfileUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *ControlUserProfileUpdate) SetUsername(v string) *ControlUserProfileUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ControlUserProfileUpdate) SetNillableUsername(v *string) *ControlUserProfileUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ControlUserProfileUpdate) SetNotes(v string) *ControlUserProfileUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ControlUserProfileUpdate) SetNillableNotes(v *string) *ControlUserProfileUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// Mutation returns the ControlUserProfileMutation object of the builder.
func (_u *ControlUserProfileUpdate) Mutation() *ControlUserProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ControlUserProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ControlUserProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ControlUserProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ControlUserProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ControlUserProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := controluserprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ControlUserProfileUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := controluserprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ControlUserProfile.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := controluserprofile.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ControlUserProfile.username": %w`, err)}
		}
	}
	return nil
}

func (_u *ControlUserProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(controluserprofile.Table, controluserprofile.Columns, sqlgraph.NewFieldSpec(controluserprofile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(controluserprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LegacyUserID(); ok {
		_spec.SetField(controluserprofile.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLegacyUserID(); ok {
		_spec.AddField(controluserprofile.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(controluserprofile.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(controluserprofile.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(controluserprofile.FieldNotes, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{controluserprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ControlUserProfileUpdateOne is the builder for updating a single ControlUserProfile entity.
type ControlUserProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ControlUserProfileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ControlUserProfileUpdateOne) SetUpdatedAt(v time.Time) *ControlUserProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_u *ControlUserProfileUpdateOne) SetLegacyUserID(v int64) *ControlUserProfileUpdateOne {
	_u.mutation.ResetLegacyUserID()
	_u.mutation.SetLegacyUserID(v)
	return _u
}

// SetNillableLegacyUserID sets the "legacy_user_id" field if the given value is not nil.
func (_u *ControlUserProfileUpdateOne) SetNillableLegacyUserID(v *int64) *ControlUserProfileUpdateOne {
	if v != nil {
		_u.SetLegacyUserID(*v)
	}
	return _u
}

// AddLegacyUserID adds value to the "legacy_user_id" field.
func (_u *ControlUserProfileUpdateOne) AddLegacyUserID(v int64) *ControlUserProfileUpdateOne {
	_u.mutation.AddLegacyUserID(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *ControlUserProfileUpdateOne) SetEmail(v string) *ControlUserProfileUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ControlUserProfileUpdateOne) SetNillableEmail(v *string) *ControlUserProfileUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *ControlUserProfileUpdateOne) SetUsername(v string) *ControlUserProfileUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ControlUserProfileUpdateOne) SetNillableUsername(v *string) *ControlUserProfileUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ControlUserProfileUpdateOne) SetNotes(v string) *ControlUserProfileUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ControlUserProfileUpdateOne) SetNillableNotes(v *string) *ControlUserProfileUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// Mutation returns the ControlUserProfileMutation object of the builder.
func (_u *ControlUserProfileUpdateOne) Mutation() *ControlUserProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the ControlUserProfileUpdate builder.
func (_u *ControlUserProfileUpdateOne) Where(ps ...predicate.ControlUserProfile) *ControlUserProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ControlUserProfileUpdateOne) Select(field string, fields ...string) *ControlUserProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ControlUserProfile entity.
func (_u *ControlUserProfileUpdateOne) Save(ctx context.Context) (*ControlUserProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ControlUserProfileUpdateOne) SaveX(ctx context.Context) *ControlUserProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ControlUserProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ControlUserProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ControlUserProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := controluserprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ControlUserProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := controluserprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ControlUserProfile.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := controluserprofile.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ControlUserProfile.username": %w`, err)}
		}
	}
	return nil
}

func (_u *ControlUserProfileUpdateOne) sqlSave(ctx context.Context) (_node *ControlUserProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(controluserprofile.Table, controluserprofile.Columns, sqlgraph.NewFieldSpec(controluserprofile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ControlUserProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, controluserprofile.FieldID)
		for _, f := range fields {
			if !controluserprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != controluserprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(controluserprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LegacyUserID(); ok {
		_spec.SetField(controluserprofile.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLegacyUserID(); ok {
		_spec.AddField(controluserprofile.FieldLegacyUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(controluserprofile.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(controluserprofile.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(controluserprofile.FieldNotes, field.TypeString, value)
	}
	_node = &ControlUserProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{controluserprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
