// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/controluserprofile"
	"github.com/google/uuid"
)

// ControlUserProfileCreate is the builder for creating a ControlUserProfile entity.
type ControlUserProfileCreate struct {
	config
	mutation *ControlUserProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ControlUserProfileCreate) SetCreatedAt(v time.Time) *ControlUserProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ControlUserProfileCreate) SetNillableCreatedAt(v *time.Time) *ControlUserProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ControlUserProfileCreate) SetUpdatedAt(v time.Time) *ControlUserProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ControlUserProfileCreate) SetNillableUpdatedAt(v *time.Time) *ControlUserProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (_c *ControlUserProfileCreate) SetLegacyUserID(v int64) *ControlUserProfileCreate {
	_c.mutation.SetLegacyUserID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *ControlUserProfileCreate) SetEmail(v string) *ControlUserProfileCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *ControlUserProfileCreate) SetUsername(v string) *ControlUserProfileCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *ControlUserProfileCreate) SetNillableUsername(v *string) *ControlUserProfileCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ControlUserProfileCreate) SetNotes(v string) *ControlUserProfileCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ControlUserProfileCreate) SetNillableNotes(v *string) *ControlUserProfileCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ControlUserProfileCreate) SetID(v uuid.UUID) *ControlUserProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ControlUserProfileMutation object of the builder.
func (_c *ControlUserProfileCreate) Mutation() *ControlUserProfileMutation {
	return _c.mutation
}

// Save creates the ControlUserProfile in the database.
func (_c *ControlUserProfileCreate) Save(ctx context.Context) (*ControlUserProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ControlUserProfileCreate) SaveX(ctx context.Context) *ControlUserProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ControlUserProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ControlUserProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ControlUserProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := controluserprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := controluserprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := controluserprofile.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := controluserprofile.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ControlUserProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ControlUserProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ControlUserProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.LegacyUserID(); !ok {
		return &ValidationError{Name: "legacy_user_id", err: errors.New(`ent: missing required field "ControlUserProfile.legacy_user_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ControlUserProfile.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := controluserprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ControlUserProfile.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "ControlUserProfile.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := controluserprofile.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ControlUserProfile.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "ControlUserProfile.notes"`)}
	}
	return nil
}

func (_c *ControlUserProfileCreate) sqlSave(ctx context.Context) (*ControlUserProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ControlUserProfileCreate) createSpec() (*ControlUserProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &ControlUserProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(controluserprofile.Table, sqlgraph.NewFieldSpec(controluserprofile.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(controluserprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(controluserprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LegacyUserID(); ok {
		_spec.SetField(controluserprofile.FieldLegacyUserID, field.TypeInt64, value)
		_node.LegacyUserID = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(controluserprofile.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(controluserprofile.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(controluserprofile.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ControlUserProfile.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ControlUserProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ControlUserProfileCreate) OnConflict(opts ...sql.ConflictOption) *ControlUserProfileUpsertOne {
	_c.conflict = opts
	return &ControlUserProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ControlUserProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ControlUserProfileCreate) OnConflictColumns(columns ...string) *ControlUserProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ControlUserProfileUpsertOne{
		create: _c,
	}
}

type (
	// ControlUserProfileUpsertOne is the builder for "upsert"-ing
	//  one ControlUserProfile node.
	ControlUserProfileUpsertOne struct {
		create *ControlUserProfileCreate
	}

	// ControlUserProfileUpsert is the "OnConflict" setter.
	ControlUserProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ControlUserProfileUpsert) SetUpdatedAt(v time.Time) *ControlUserProfileUpsert {
	u.Set(controluserprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ControlUserProfileUpsert) UpdateUpdatedAt() *ControlUserProfileUpsert {
	u.SetExcluded(controluserprofile.FieldUpdatedAt)
	return u
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *ControlUserProfileUpsert) SetLegacyUserID(v int64) *ControlUserProfileUpsert {
	u.Set(controluserprofile.FieldLegacyUserID, v)
	return u
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *ControlUserProfileUpsert) UpdateLegacyUserID() *ControlUserProfileUpsert {
	u.SetExcluded(controluserprofile.FieldLegacyUserID)
	return u
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *ControlUserProfileUpsert) AddLegacyUserID(v int64) *ControlUserProfileUpsert {
	u.Add(controluserprofile.FieldLegacyUserID, v)
	return u
}

// SetEmail sets the "email" field.
func (u *ControlUserProfileUpsert) SetEmail(v string) *ControlUserProfileUpsert {
	u.Set(controluserprofile.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ControlUserProfileUpsert) UpdateEmail() *ControlUserProfileUpsert {
	u.SetExcluded(controluserprofile.FieldEmail)
	return u
}

// SetUsername sets the "username" field.
func (u *ControlUserProfileUpsert) SetUsername(v string) *ControlUserProfileUpsert {
	u.Set(controluserprofile.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ControlUserProfileUpsert) UpdateUsername() *ControlUserProfileUpsert {
	u.SetExcluded(controluserprofile.FieldUsername)
	return u
}

// SetNotes sets the "notes" field.
func (u *ControlUserProfileUpsert) SetNotes(v string) *ControlUserProfileUpsert {
	u.Set(controluserprofile.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ControlUserProfileUpsert) UpdateNotes() *ControlUserProfileUpsert {
	u.SetExcluded(controluserprofile.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ControlUserProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(controluserprofile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ControlUserProfileUpsertOne) UpdateNewValues() *ControlUserProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(controluserprofile.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(controluserprofile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ControlUserProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ControlUserProfileUpsertOne) Ignore() *ControlUserProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ControlUserProfileUpsertOne) DoNothing() *ControlUserProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ControlUserProfileCreate.OnConflict
// documentation for more info.
func (u *ControlUserProfileUpsertOne) Update(set func(*ControlUserProfileUpsert)) *ControlUserProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ControlUserProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ControlUserProfileUpsertOne) SetUpdatedAt(v time.Time) *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ControlUserProfileUpsertOne) UpdateUpdatedAt() *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *ControlUserProfileUpsertOne) SetLegacyUserID(v int64) *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *ControlUserProfileUpsertOne) AddLegacyUserID(v int64) *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *ControlUserProfileUpsertOne) UpdateLegacyUserID() *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetEmail sets the "email" field.
func (u *ControlUserProfileUpsertOne) SetEmail(v string) *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ControlUserProfileUpsertOne) UpdateEmail() *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateEmail()
	})
}

// SetUsername sets the "username" field.
func (u *ControlUserProfileUpsertOne) SetUsername(v string) *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ControlUserProfileUpsertOne) UpdateUsername() *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateUsername()
	})
}

// SetNotes sets the "notes" field.
func (u *ControlUserProfileUpsertOne) SetNotes(v string) *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ControlUserProfileUpsertOne) UpdateNotes() *ControlUserProfileUpsertOne {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *ControlUserProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ControlUserProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ControlUserProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ControlUserProfileUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ControlUserProfileUpsertOne.ID is not supported by MySQL driver. Use ControlUserProfileUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ControlUserProfileUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ControlUserProfileCreateBulk is the builder for creating many ControlUserProfile entities in bulk.
type ControlUserProfileCreateBulk struct {
	config
	err      error
	builders []*ControlUserProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the ControlUserProfile entities in the database.
func (_c *ControlUserProfileCreateBulk) Save(ctx context.Context) ([]*ControlUserProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ControlUserProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ControlUserProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ControlUserProfileCreateBulk) SaveX(ctx context.Context) []*ControlUserProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ControlUserProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ControlUserProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ControlUserProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ControlUserProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ControlUserProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *ControlUserProfileUpsertBulk {
	_c.conflict = opts
	return &ControlUserProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ControlUserProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ControlUserProfileCreateBulk) OnConflictColumns(columns ...string) *ControlUserProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ControlUserProfileUpsertBulk{
		create: _c,
	}
}

// ControlUserProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of ControlUserProfile nodes.
type ControlUserProfileUpsertBulk struct {
	create *ControlUserProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ControlUserProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(controluserprofile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ControlUserProfileUpsertBulk) UpdateNewValues() *ControlUserProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(controluserprofile.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(controluserprofile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ControlUserProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ControlUserProfileUpsertBulk) Ignore() *ControlUserProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ControlUserProfileUpsertBulk) DoNothing() *ControlUserProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ControlUserProfileCreateBulk.OnConflict
// documentation for more info.
func (u *ControlUserProfileUpsertBulk) Update(set func(*ControlUserProfileUpsert)) *ControlUserProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ControlUserProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ControlUserProfileUpsertBulk) SetUpdatedAt(v time.Time) *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ControlUserProfileUpsertBulk) UpdateUpdatedAt() *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLegacyUserID sets the "legacy_user_id" field.
func (u *ControlUserProfileUpsertBulk) SetLegacyUserID(v int64) *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetLegacyUserID(v)
	})
}

// AddLegacyUserID adds v to the "legacy_user_id" field.
func (u *ControlUserProfileUpsertBulk) AddLegacyUserID(v int64) *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.AddLegacyUserID(v)
	})
}

// UpdateLegacyUserID sets the "legacy_user_id" field to the value that was provided on create.
func (u *ControlUserProfileUpsertBulk) UpdateLegacyUserID() *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateLegacyUserID()
	})
}

// SetEmail sets the "email" field.
func (u *ControlUserProfileUpsertBulk) SetEmail(v string) *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ControlUserProfileUpsertBulk) UpdateEmail() *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateEmail()
	})
}

// SetUsername sets the "username" field.
func (u *ControlUserProfileUpsertBulk) SetUsername(v string) *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ControlUserProfileUpsertBulk) UpdateUsername() *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateUsername()
	})
}

// SetNotes sets the "notes" field.
func (u *ControlUserProfileUpsertBulk) SetNotes(v string) *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ControlUserProfileUpsertBulk) UpdateNotes() *ControlUserProfileUpsertBulk {
	return u.Update(func(s *ControlUserProfileUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *ControlUserProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ControlUserProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ControlUserProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ControlUserProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
