// Code generated by ent, DO NOT EDIT.

package authpasswordresettoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubjectID applies equality check predicate on the "subject_id" field. It's identical to SubjectIDEQ.
func SubjectID(v uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldSubjectID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldEmail, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubjectIDEQ applies the EQ predicate on the "subject_id" field.
func SubjectIDEQ(v uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectIDNEQ applies the NEQ predicate on the "subject_id" field.
func SubjectIDNEQ(v uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldSubjectID, v))
}

// SubjectIDIn applies the In predicate on the "subject_id" field.
func SubjectIDIn(vs ...uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldSubjectID, vs...))
}

// SubjectIDNotIn applies the NotIn predicate on the "subject_id" field.
func SubjectIDNotIn(vs ...uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldSubjectID, vs...))
}

// SubjectIDGT applies the GT predicate on the "subject_id" field.
func SubjectIDGT(v uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldSubjectID, v))
}

// SubjectIDGTE applies the GTE predicate on the "subject_id" field.
func SubjectIDGTE(v uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldSubjectID, v))
}

// SubjectIDLT applies the LT predicate on the "subject_id" field.
func SubjectIDLT(v uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldSubjectID, v))
}

// SubjectIDLTE applies the LTE predicate on the "subject_id" field.
func SubjectIDLTE(v uuid.UUID) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldSubjectID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldContainsFold(FieldEmail, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.FieldNotNull(FieldConsumedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthPasswordResetToken) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthPasswordResetToken) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthPasswordResetToken) predicate.AuthPasswordResetToken {
	return predicate.AuthPasswordResetToken(sql.NotPredicates(p))
}
