// Code generated by ent, DO NOT EDIT.

package authmfatotpfactor

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the authmfatotpfactor type in the database.
	Label = "auth_mfatotp_factor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "subject_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSecretEncrypted holds the string denoting the secret_encrypted field in the database.
	FieldSecretEncrypted = "secret_encrypted"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldEnabledAt holds the string denoting the enabled_at field in the database.
	FieldEnabledAt = "enabled_at"
	// Table holds the table name of the authmfatotpfactor in the database.
	Table = "auth_mfa_totp_factors"
)

// Columns holds all SQL columns for authmfatotpfactor fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSecretEncrypted,
	FieldEnabled,
	FieldEnabledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the AuthMFATOTPFactor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySecretEncrypted orders the results by the secret_encrypted field.
func BySecretEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretEncrypted, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByEnabledAt orders the results by the enabled_at field.
func ByEnabledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabledAt, opts...).ToFunc()
}
