// Code generated by ent, DO NOT EDIT.

package authmfatotpfactor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldUpdatedAt, v))
}

// SecretEncrypted applies equality check predicate on the "secret_encrypted" field. It's identical to SecretEncryptedEQ.
func SecretEncrypted(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldSecretEncrypted, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldEnabled, v))
}

// EnabledAt applies equality check predicate on the "enabled_at" field. It's identical to EnabledAtEQ.
func EnabledAt(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldEnabledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLTE(FieldUpdatedAt, v))
}

// SecretEncryptedEQ applies the EQ predicate on the "secret_encrypted" field.
func SecretEncryptedEQ(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldSecretEncrypted, v))
}

// SecretEncryptedNEQ applies the NEQ predicate on the "secret_encrypted" field.
func SecretEncryptedNEQ(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNEQ(FieldSecretEncrypted, v))
}

// SecretEncryptedIn applies the In predicate on the "secret_encrypted" field.
func SecretEncryptedIn(vs ...string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldIn(FieldSecretEncrypted, vs...))
}

// SecretEncryptedNotIn applies the NotIn predicate on the "secret_encrypted" field.
func SecretEncryptedNotIn(vs ...string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNotIn(FieldSecretEncrypted, vs...))
}

// SecretEncryptedGT applies the GT predicate on the "secret_encrypted" field.
func SecretEncryptedGT(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGT(FieldSecretEncrypted, v))
}

// SecretEncryptedGTE applies the GTE predicate on the "secret_encrypted" field.
func SecretEncryptedGTE(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGTE(FieldSecretEncrypted, v))
}

// SecretEncryptedLT applies the LT predicate on the "secret_encrypted" field.
func SecretEncryptedLT(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLT(FieldSecretEncrypted, v))
}

// SecretEncryptedLTE applies the LTE predicate on the "secret_encrypted" field.
func SecretEncryptedLTE(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLTE(FieldSecretEncrypted, v))
}

// SecretEncryptedContains applies the Contains predicate on the "secret_encrypted" field.
func SecretEncryptedContains(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldContains(FieldSecretEncrypted, v))
}

// SecretEncryptedHasPrefix applies the HasPrefix predicate on the "secret_encrypted" field.
func SecretEncryptedHasPrefix(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldHasPrefix(FieldSecretEncrypted, v))
}

// SecretEncryptedHasSuffix applies the HasSuffix predicate on the "secret_encrypted" field.
func SecretEncryptedHasSuffix(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldHasSuffix(FieldSecretEncrypted, v))
}

// SecretEncryptedIsNil applies the IsNil predicate on the "secret_encrypted" field.
func SecretEncryptedIsNil() predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldIsNull(FieldSecretEncrypted))
}

// SecretEncryptedNotNil applies the NotNil predicate on the "secret_encrypted" field.
func SecretEncryptedNotNil() predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNotNull(FieldSecretEncrypted))
}

// SecretEncryptedEqualFold applies the EqualFold predicate on the "secret_encrypted" field.
func SecretEncryptedEqualFold(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEqualFold(FieldSecretEncrypted, v))
}

// SecretEncryptedContainsFold applies the ContainsFold predicate on the "secret_encrypted" field.
func SecretEncryptedContainsFold(v string) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldContainsFold(FieldSecretEncrypted, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNEQ(FieldEnabled, v))
}

// EnabledAtEQ applies the EQ predicate on the "enabled_at" field.
func EnabledAtEQ(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldEQ(FieldEnabledAt, v))
}

// EnabledAtNEQ applies the NEQ predicate on the "enabled_at" field.
func EnabledAtNEQ(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNEQ(FieldEnabledAt, v))
}

// EnabledAtIn applies the In predicate on the "enabled_at" field.
func EnabledAtIn(vs ...time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldIn(FieldEnabledAt, vs...))
}

// EnabledAtNotIn applies the NotIn predicate on the "enabled_at" field.
func EnabledAtNotIn(vs ...time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNotIn(FieldEnabledAt, vs...))
}

// EnabledAtGT applies the GT predicate on the "enabled_at" field.
func EnabledAtGT(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGT(FieldEnabledAt, v))
}

// EnabledAtGTE applies the GTE predicate on the "enabled_at" field.
func EnabledAtGTE(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldGTE(FieldEnabledAt, v))
}

// EnabledAtLT applies the LT predicate on the "enabled_at" field.
func EnabledAtLT(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLT(FieldEnabledAt, v))
}

// EnabledAtLTE applies the LTE predicate on the "enabled_at" field.
func EnabledAtLTE(v time.Time) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldLTE(FieldEnabledAt, v))
}

// EnabledAtIsNil applies the IsNil predicate on the "enabled_at" field.
func EnabledAtIsNil() predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldIsNull(FieldEnabledAt))
}

// EnabledAtNotNil applies the NotNil predicate on the "enabled_at" field.
func EnabledAtNotNil() predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.FieldNotNull(FieldEnabledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthMFATOTPFactor) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthMFATOTPFactor) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthMFATOTPFactor) predicate.AuthMFATOTPFactor {
	return predicate.AuthMFATOTPFactor(sql.NotPredicates(p))
}
