// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/health"
	"github.com/Wei-Shaw/sub2api/internal/pkg/otel"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"log"
	"sync"
	"time"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeBillingApplication() (*BillingApplication, error) {
	configConfig, err := config.ProvideBillingConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	redisClient := repository.ProvideRedis(configConfig)
	checker := health.NewChecker(db, redisClient)
	provider, err := otel.ProvideOtel(configConfig)
	if err != nil {
		return nil, err
	}
	metricsServer := otel.ProvideMetricsServer(configConfig, provider)
	billingDB, err := repository.ProvideBillingDB(configConfig)
	if err != nil {
		return nil, err
	}
	billingEventConsumer := repository.NewRedisBillingEventConsumer(redisClient, configConfig)
	usageBillingRepository := repository.NewUsageBillingRepository(billingDB)
	billingCache := repository.NewBillingCache(redisClient)
	userRepository := repository.NewUserRepository(client, db)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	billingCacheService := service.NewBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, configConfig)
	schedulerCache := repository.NewSchedulerCache(redisClient)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	timingWheelService, err := service.ProvideBillingTimingWheelService()
	if err != nil {
		return nil, err
	}
	deferredService := service.ProvideBillingDeferredService(accountRepository, timingWheelService)
	groupRepository := repository.NewGroupRepository(client, db)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	apiKeyService := service.NewAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, apiKeyCache, configConfig)
	apiKeyAuthCacheInvalidator := service.ProvideBillingAPIKeyAuthCacheInvalidator(apiKeyService)
	billingConsumerService := service.NewBillingConsumerService(billingEventConsumer, usageBillingRepository, billingCacheService, deferredService, apiKeyAuthCacheInvalidator)
	v := provideBillingCleanup(client, redisClient, provider, metricsServer, billingDB, billingConsumerService, billingCacheService, deferredService)
	billingApplication := &BillingApplication{
		Health:  checker,
		Cleanup: v,
	}
	return billingApplication, nil
}

// wire.go:

// BillingApplication is the top-level struct for the billing binary.
type BillingApplication struct {
	Health  *health.Checker
	Cleanup func()
}

func provideBillingCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	otelProvider *otel.Provider,
	metricsServer *otel.MetricsServer,
	billingDB *repository.BillingDB,
	billingConsumer *service.BillingConsumerService,
	billingCache *service.BillingCacheService,
	deferredService *service.DeferredService,
) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()

		type cleanupStep struct {
			name string
			fn   func() error
		}

		parallelSteps := []cleanupStep{
			{"BillingConsumerService", func() error {
				if billingConsumer != nil {
					billingConsumer.Stop()
				}
				return nil
			}},
			{"BillingCacheService", func() error {
				if billingCache != nil {
					billingCache.Stop()
				}
				return nil
			}},
			{"DeferredService", func() error {
				if deferredService != nil {
					deferredService.Stop()
				}
				return nil
			}},
		}

		infraSteps := []cleanupStep{
			{"BillingDB", func() error {
				if billingDB != nil {
					return billingDB.Close()
				}
				return nil
			}},
			{"Redis", func() error {
				if rdb == nil {
					return nil
				}
				return rdb.Close()
			}},
			{"Ent", func() error {
				if entClient == nil {
					return nil
				}
				return entClient.Close()
			}},
		}

		runParallel := func(steps []cleanupStep) {
			var wg sync.WaitGroup
			for i := range steps {
				step := steps[i]
				wg.Add(1)
				go func() {
					defer wg.Done()
					if err := step.fn(); err != nil {
						log.Printf("[Cleanup] %s failed: %v", step.name, err)
						return
					}
					log.Printf("[Cleanup] %s succeeded", step.name)
				}()
			}
			wg.Wait()
		}

		runSequential := func(steps []cleanupStep) {
			for i := range steps {
				step := steps[i]
				if err := step.fn(); err != nil {
					log.Printf("[Cleanup] %s failed: %v", step.name, err)
					continue
				}
				log.Printf("[Cleanup] %s succeeded", step.name)
			}
		}

		runParallel(parallelSteps)

		if otelProvider != nil {
			if err := otelProvider.Shutdown(ctx); err != nil {
				log.Printf("OTel provider shutdown error: %v", err)
			}
		}
		if metricsServer != nil {
			if err := metricsServer.Shutdown(ctx); err != nil {
				log.Printf("Metrics server shutdown error: %v", err)
			}
		}

		runSequential(infraSteps)

		select {
		case <-ctx.Done():
			log.Printf("[Cleanup] Warning: cleanup timed out after 30 seconds")
		default:
			log.Printf("[Cleanup] All cleanup steps completed")
		}
	}
}
