// Code generated by ent, DO NOT EDIT.

package authregistrationchallenge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldProvider, v))
}

// Issuer applies equality check predicate on the "issuer" field. It's identical to IssuerEQ.
func Issuer(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldIssuer, v))
}

// ExternalSubject applies equality check predicate on the "external_subject" field. It's identical to ExternalSubjectEQ.
func ExternalSubject(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldExternalSubject, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldEmail, v))
}

// RegistrationEmail applies equality check predicate on the "registration_email" field. It's identical to RegistrationEmailEQ.
func RegistrationEmail(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldRegistrationEmail, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldUsername, v))
}

// RedirectTo applies equality check predicate on the "redirect_to" field. It's identical to RedirectToEQ.
func RedirectTo(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldRedirectTo, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContainsFold(FieldProvider, v))
}

// IssuerEQ applies the EQ predicate on the "issuer" field.
func IssuerEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldIssuer, v))
}

// IssuerNEQ applies the NEQ predicate on the "issuer" field.
func IssuerNEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldIssuer, v))
}

// IssuerIn applies the In predicate on the "issuer" field.
func IssuerIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldIssuer, vs...))
}

// IssuerNotIn applies the NotIn predicate on the "issuer" field.
func IssuerNotIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldIssuer, vs...))
}

// IssuerGT applies the GT predicate on the "issuer" field.
func IssuerGT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldIssuer, v))
}

// IssuerGTE applies the GTE predicate on the "issuer" field.
func IssuerGTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldIssuer, v))
}

// IssuerLT applies the LT predicate on the "issuer" field.
func IssuerLT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldIssuer, v))
}

// IssuerLTE applies the LTE predicate on the "issuer" field.
func IssuerLTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldIssuer, v))
}

// IssuerContains applies the Contains predicate on the "issuer" field.
func IssuerContains(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContains(FieldIssuer, v))
}

// IssuerHasPrefix applies the HasPrefix predicate on the "issuer" field.
func IssuerHasPrefix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasPrefix(FieldIssuer, v))
}

// IssuerHasSuffix applies the HasSuffix predicate on the "issuer" field.
func IssuerHasSuffix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasSuffix(FieldIssuer, v))
}

// IssuerEqualFold applies the EqualFold predicate on the "issuer" field.
func IssuerEqualFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEqualFold(FieldIssuer, v))
}

// IssuerContainsFold applies the ContainsFold predicate on the "issuer" field.
func IssuerContainsFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContainsFold(FieldIssuer, v))
}

// ExternalSubjectEQ applies the EQ predicate on the "external_subject" field.
func ExternalSubjectEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldExternalSubject, v))
}

// ExternalSubjectNEQ applies the NEQ predicate on the "external_subject" field.
func ExternalSubjectNEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldExternalSubject, v))
}

// ExternalSubjectIn applies the In predicate on the "external_subject" field.
func ExternalSubjectIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldExternalSubject, vs...))
}

// ExternalSubjectNotIn applies the NotIn predicate on the "external_subject" field.
func ExternalSubjectNotIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldExternalSubject, vs...))
}

// ExternalSubjectGT applies the GT predicate on the "external_subject" field.
func ExternalSubjectGT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldExternalSubject, v))
}

// ExternalSubjectGTE applies the GTE predicate on the "external_subject" field.
func ExternalSubjectGTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldExternalSubject, v))
}

// ExternalSubjectLT applies the LT predicate on the "external_subject" field.
func ExternalSubjectLT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldExternalSubject, v))
}

// ExternalSubjectLTE applies the LTE predicate on the "external_subject" field.
func ExternalSubjectLTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldExternalSubject, v))
}

// ExternalSubjectContains applies the Contains predicate on the "external_subject" field.
func ExternalSubjectContains(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContains(FieldExternalSubject, v))
}

// ExternalSubjectHasPrefix applies the HasPrefix predicate on the "external_subject" field.
func ExternalSubjectHasPrefix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasPrefix(FieldExternalSubject, v))
}

// ExternalSubjectHasSuffix applies the HasSuffix predicate on the "external_subject" field.
func ExternalSubjectHasSuffix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasSuffix(FieldExternalSubject, v))
}

// ExternalSubjectEqualFold applies the EqualFold predicate on the "external_subject" field.
func ExternalSubjectEqualFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEqualFold(FieldExternalSubject, v))
}

// ExternalSubjectContainsFold applies the ContainsFold predicate on the "external_subject" field.
func ExternalSubjectContainsFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContainsFold(FieldExternalSubject, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContainsFold(FieldEmail, v))
}

// RegistrationEmailEQ applies the EQ predicate on the "registration_email" field.
func RegistrationEmailEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldRegistrationEmail, v))
}

// RegistrationEmailNEQ applies the NEQ predicate on the "registration_email" field.
func RegistrationEmailNEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldRegistrationEmail, v))
}

// RegistrationEmailIn applies the In predicate on the "registration_email" field.
func RegistrationEmailIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldRegistrationEmail, vs...))
}

// RegistrationEmailNotIn applies the NotIn predicate on the "registration_email" field.
func RegistrationEmailNotIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldRegistrationEmail, vs...))
}

// RegistrationEmailGT applies the GT predicate on the "registration_email" field.
func RegistrationEmailGT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldRegistrationEmail, v))
}

// RegistrationEmailGTE applies the GTE predicate on the "registration_email" field.
func RegistrationEmailGTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldRegistrationEmail, v))
}

// RegistrationEmailLT applies the LT predicate on the "registration_email" field.
func RegistrationEmailLT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldRegistrationEmail, v))
}

// RegistrationEmailLTE applies the LTE predicate on the "registration_email" field.
func RegistrationEmailLTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldRegistrationEmail, v))
}

// RegistrationEmailContains applies the Contains predicate on the "registration_email" field.
func RegistrationEmailContains(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContains(FieldRegistrationEmail, v))
}

// RegistrationEmailHasPrefix applies the HasPrefix predicate on the "registration_email" field.
func RegistrationEmailHasPrefix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasPrefix(FieldRegistrationEmail, v))
}

// RegistrationEmailHasSuffix applies the HasSuffix predicate on the "registration_email" field.
func RegistrationEmailHasSuffix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasSuffix(FieldRegistrationEmail, v))
}

// RegistrationEmailEqualFold applies the EqualFold predicate on the "registration_email" field.
func RegistrationEmailEqualFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEqualFold(FieldRegistrationEmail, v))
}

// RegistrationEmailContainsFold applies the ContainsFold predicate on the "registration_email" field.
func RegistrationEmailContainsFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContainsFold(FieldRegistrationEmail, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContainsFold(FieldUsername, v))
}

// RedirectToEQ applies the EQ predicate on the "redirect_to" field.
func RedirectToEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldRedirectTo, v))
}

// RedirectToNEQ applies the NEQ predicate on the "redirect_to" field.
func RedirectToNEQ(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldRedirectTo, v))
}

// RedirectToIn applies the In predicate on the "redirect_to" field.
func RedirectToIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldRedirectTo, vs...))
}

// RedirectToNotIn applies the NotIn predicate on the "redirect_to" field.
func RedirectToNotIn(vs ...string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldRedirectTo, vs...))
}

// RedirectToGT applies the GT predicate on the "redirect_to" field.
func RedirectToGT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldRedirectTo, v))
}

// RedirectToGTE applies the GTE predicate on the "redirect_to" field.
func RedirectToGTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldRedirectTo, v))
}

// RedirectToLT applies the LT predicate on the "redirect_to" field.
func RedirectToLT(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldRedirectTo, v))
}

// RedirectToLTE applies the LTE predicate on the "redirect_to" field.
func RedirectToLTE(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldRedirectTo, v))
}

// RedirectToContains applies the Contains predicate on the "redirect_to" field.
func RedirectToContains(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContains(FieldRedirectTo, v))
}

// RedirectToHasPrefix applies the HasPrefix predicate on the "redirect_to" field.
func RedirectToHasPrefix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasPrefix(FieldRedirectTo, v))
}

// RedirectToHasSuffix applies the HasSuffix predicate on the "redirect_to" field.
func RedirectToHasSuffix(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldHasSuffix(FieldRedirectTo, v))
}

// RedirectToEqualFold applies the EqualFold predicate on the "redirect_to" field.
func RedirectToEqualFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEqualFold(FieldRedirectTo, v))
}

// RedirectToContainsFold applies the ContainsFold predicate on the "redirect_to" field.
func RedirectToContainsFold(v string) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldContainsFold(FieldRedirectTo, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.FieldNotNull(FieldConsumedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthRegistrationChallenge) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthRegistrationChallenge) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthRegistrationChallenge) predicate.AuthRegistrationChallenge {
	return predicate.AuthRegistrationChallenge(sql.NotPredicates(p))
}
