{{- if .Values.control.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "robust2api.controlAPIServiceName" . }}
  labels:
    {{- include "robust2api.labels" . | nindent 4 }}
    app.kubernetes.io/component: control
spec:
  type: {{ .Values.controlAPIService.type }}
  ports:
    - port: {{ .Values.controlAPIService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robust2api.control.selectorLabels" . | nindent 4 }}
{{- end }}
